### ISSUE TITLE
Zitierweise

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#10]
_From @kadowa on February 25, 2016 14:32_

Die empfohlene Zitierweise in heiUP ist nicht korrekt. Erwünscht ist

```
Nachname, Vorname, Titel. Ort: Verlag, 2017.
```

Besonderheiten ergeben sich bei Sammelbänden:

```
Young, Glenn, ed. The Best American Short Plays, 2002–2003. New York: Applause, 2007.
```

oder

```
Bonnefoy, Yves. New and Selected Poems. Edited by John Naughton and Anthony Rudolf. Chicago: University of Chicago Press, 1995.
```

@AnjaKonopka, habe ich das so korrekt übertragen? Gibt es schon eine Entscheidung für einen der beiden Zitierstile bei Sammelbänden?

_Copied from original issue: UB-Heidelberg/UBHD-OMPPropylaeum#7_

**Comment by kadowa** [comment]
@AnjaKonopka, wie verbinde ich denn mehrere Autoren oder Herausgeber? Mit Komma? 'Und'/'And'?

Mit Komma wirkt es etwas unübersichtlich, finde ich:

http://heiup.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog/book/53

**Comment by kadowa** [comment]
_From @AnjaKonopka on February 25, 2016 15:33_

nach CMOS ist vorgesehen, bei bis zu zwei Autoren bzw. Herausgebern ein
"und" zu setzen, bei mehr als zweien die ersten beiden durch Komma
voneinander zu trennen und den letzten mit und anzufügen.

**Comment by kadowa** [comment]
Ok, danke. Einfach geht aber anders. :smile:

**Comment by kadowa** [comment]
_From @AnjaKonopka on February 29, 2016 12:39_

**AKTUALISIERT AM 25.04.2016**

Für das PDF sollte so zitiert werden:

Empfohlene Zitierweise (PDF)

Monographie: 
Nachname, Vorname: _Titel: Untertitel,_ Verlagsort: Verlag,  Jahr. doi:xx

Sammelband: 
Nachname, Vorname (Hrsg).:_Titel: Untertitel,_ Verlagsort: Verlag, Jahr. doi:xx

Auflagenkennung (wenn nicht die erste Auflage)
Nachname, Vorname: _Titel: Untertitel,_ 2., ergänzte Aufl., Ort: Verlag, Jahr. doi:xx

Werk mit zwei oder drei Autoren:
Nachname, Vorname / Nachname, Vorname / Nachname, Vorname: _Titel: Untertitel,_ Ort: Verlag, Jahr. doi:xx

Werk mit mehr als drei Autoren/Herausgebern
Nachname, Vorname  et al.: _Titel: Untertitel,_ Ort: Verlag, Jahr. doi:xx

Werk, das in einer Reihe erscheint:
Nachname, Vorname: _Titel: Untertitel,_ Ort: Verlag,  Jahr (Reihe, Bd. x). doi:xx

Bei der empfohlenen Zitierweise beziehen wir uns grundsätzlich auf das PDF.

**Comment by kadowa** [comment]
_From @AnjaKonopka on February 29, 2016 12:42_

Liebe Katharina, da dieser Zitierissue natürlich nicht nur Propylaeum, sondern auch alle anderen "Verlage" betrifft: Könntest Du ein allgemeineres Portal umziehen?

**Comment by kadowa** [comment]
Ausgabe von Erscheinungsjahr und ISBN der verschiedenen Publikationsformate in der linken Spalte unterhalb von "Empfohlene Zitierweise". Die empfohlene Zitierweise bezieht sich stets auf das PDF:

Empfohlene Zitierweise (PDF)

Nachname, Vorname: Titel:_Untertitel, Ort: Verlag, Jahr. doi:xx

ISBN

Bei den ISBNs nennen wir alle vorhandenen, und zwar in der Form (unterhalb der CC-Lizenz):

ISBN: 9783946054016 (PDF) [vom Reiter PDF]
ISBN: xxxx (Softcover) [-> vom Reiter Softcover]
ISBN: xxxx (Hardcover) [-> vom Reiter Hardcover]
ISBN: xxx (Originalausgabe) [vom Reiter Originalausgabe]
Erscheinungsdatum

Unterhalb von "Veröffentlicht am 23.07.2015" steht:

Erschienen als:
PDF yyyy [yyyy = Publication date vom Reiter PDF]
Softcover yyyy [yyyy = Date of publication vom Reiter Softcover]
Hardcover yyyy [yyyy = Date of publication vom Reiter Hardcover]

Die Originalausgabe erschien yyyy [= Date of first publication vom Reiter Originalausgabe] bei Verlagsname [= Verlagsname von diesem Reiter].

Das Erscheinungsjahr des PDF ziehen wir vom Reiter PDF, dort ist es "Publication date".
Das Erscheinungsjahr der Originalausgabe vom Reiter "Originalausgabe", dort wird auch die ISBN und der Verlag angegeben, als Bezug für das Datum wählen wir "Date of first publication"
Das Erscheinungsjahr der PoD-Veröffentlichung von einem Reiter "Softcover" oder "Hardcover" (je nachdem, was es ist) aus dem Feld publication date. Auf diesem Reiter sollten wir ebenfalls ISBN und Verlag eingeben.

**Comment by kadowa** [comment]
@AnjaKonopka, könntest du https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/7#issuecomment-191317356 in ein eigenes Issue kopieren? Die Publikationsformate sind ein separates Thema.

**Comment by kadowa** [comment]
Wie soll eigentlich die Anzeige in unterschiedlichen Sprachen gehandhabt werden? Ändert sich die Zitierweise, wenn die Seite auf Englisch aufgerufen wird?

Generell wäre es eigentlich auch schön, die Zitation in verschiedenen Formaten zum Herunterladen anzubieten, z.B. in Bibtex. Aber das ist eine etwas aufwändigere Geschichte.

**Comment by kadowa** [comment]
_From @AnjaKonopka on March 9, 2016 10:3_

Ich habe die Beispiele für Musterzitationen (Comment vom 29. Februar) 
noch einmal überarbeitet. CMOS ist irgendwie maximal kompliziert :-(

Für die englische Seite sind folgende Anpassungen nötig:

Hrsg.  (einer) -> ed.
Hrsg. (mehrere) -> eds.
und -> and
vor "and" ein Komma.
Bd. -> vol.

Jacobs, Sue-Ellen, Wesley Thomas, and Sabine Lang, eds. /Two-Spirit 
People: Native American Gender Identity, Sexuality, and Spirituality/. 
Urbana: University of Illinois Press, 1997.

Zitation in verschiedenen Formaten zum Herunterladen finde ich natürlich 
eine sehr charmante Sache, aber ich würde es im Moment zurückstellen, da 
es so vieles anderes gibt, was uns unter den Nägeln brennt.

**Comment by kadowa** [comment]
Bis auf Reihentitel und Bandnummer ist alles umgesetzt. @AnjaKonopka, kannst du alle Publikationen prüfen? Das einzige Problem sind noch die fehlenden Übersetzungen für 'and', 'eds' und 'ed'. Sobald ich diese in die Lokalisierungs-Datei eintrage, fehlen plötzlich sämtliche deutsche Übersetzungen. Da ich das für das größere Übel halte, habe ich die Übersetzungen jetzt erstmal weggelassen. Wenn alles ok ist, können wir die Änderungen Montag hoffentlich ins Produktiv-System umziehen.

**Comment by kadowa** [comment]
Übersetzungen sind da, Reihentitel folgt hoffentlich heute ...

**Comment by kadowa** [comment]
@AnjaKonopka, leider muss ich dich schon wieder in die Untiefen von CMS schicken. Wie wird denn im Englischen die Reihe zitiert? "Vol."? "vol."? Und wie gehe ich mit dem Untertitel um?

**Comment by kadowa** [comment]
_From @AnjaKonopka on March 14, 2016 11:2_

"vol" klein. Zwischen Titel und Untertitel bitte einen Punkt setzen.

**Comment by kadowa** [comment]
Ist umgesetzt: https://github.com/UB-Heidelberg/UBHD-OMPHeibooks/commit/033ece266dc5f8e7e761bb73392be530a481fffd

Damit wäre erstmal alles abgehakt, wenn ich das richtig sehe. @AnjaKonopka, kann ich das Issue damit schließen?

**Comment by kadowa** [comment]
_From @AnjaKonopka on March 14, 2016 14:4_

  @kadowa: Super, das sieht schon sehr gut aus! Die CC-Lizenz wird im Moment
aber noch zwei mal als Link angezeigt und beide Links funktionieren - kann
man einen streichen?

**Comment by kadowa** [comment]
_From @AnjaKonopka on March 14, 2016 15:8_

@kadowa, Im Moment ist ide Ausgabe von Werken mit mehr als zwei Autoren bzw. Herausgebern so
Autorname, Vorname, **Nachname, Vorname** und Vorname Nachname. Titel: Untertitel. Ort: Verlag, Jahr. doi. 
programmiert.

Gewünscht ist aber: 
Autorname, Vorname, **Vorname Nachname** und Vorname Nachname. Titel: Untertitel. Ort: Verlag, Jahr. doi.

**Comment by kadowa** [comment]
_From @AnjaKonopka on March 14, 2016 15:11_

@kadowa 

Ausgegeben werden soll ja:

Wenn es Herausgeber und Autoren gibt: Nur die Herausgeber.
Wenn es mehr als drei Herausgeber gibt. Nur die ersten drei.
Wenn es mehr als drei Autoren gibt: Auch die ersten drei.

Zusätzlicher Wunsch meinerseits: Wenn es mehr als drei Autoren bzw. Herausgeber gibt, bitte "et. al." anfügen. (Bei der empfohlenen Zitierweise und im Haupttext).

**Comment by kadowa** [comment]
"et al." ist jetzt bei der Zitierweise drin. Was genau ist denn mit "im Haupttext" gemeint?

**Comment by kadowa** [comment]
_From @AnjaKonopka on March 16, 2016 8:39_

Danke!! Mit "Haupttext" meinte ich die Informationen, die rechts vom 
Bild angezeigt werden.

**Comment by kadowa** [comment]
_From @AnjaKonopka on March 16, 2016 8:47_

Leider werden im Moment noch alle Autoren ausgegeben:

http://heiup.uni-heidelberg.de/UBHD_OMPHeibooks/catalog/book/62

Dabei macht es keinen Unterschied, ob ich den Haken bei "Edit in browse 
lists" gesetzt habe oder nicht.

**Comment by kadowa** [comment]
Ja, in der Überschrift, aber bei der Zitierweise nicht. Da es in diesem Issue um die Zitation geht, hatte ich nur diese Baustelle im Kopf. Das andere betrifft nämlich mindestens noch die Katalog- und Bändeansicht ebenso, oder? Dafür sollten wir #4 wieder öffnen.

**Comment by nils-stefan-weiher** [comment]
@AnjaKonopka 
Ich habe jetzt nochmal nur für heiup die Anzeige der Zitierweise geändert. Das ist aber jetzt nur oberflächlich angepasst und muss später nochmal überarbeitet werden, damit es intern einheitlich mit den anderen Projekten ist.
Unter http://heiup.uni-heidelberg.de/UBHD_OMPPortal/catalog/book/43 kann man die Änderungen sehen.
Wenn das so passt würde ich heiup so aktualisieren bis spätestens Donnerstag.

**Comment by nils-stefan-weiher** [comment]
@AnjaKonopka 
Die Änderungen sind jetzt auch in der produktiven Instanz von heiup:
http://heiup.uni-heidelberg.de/catalog/book/43

**Comment by kadowa** [comment]
S. #51.
