### ISSUE TITLE
Auflagenzählung

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#101]
In OMP 1.2 sehe ich zurzeit kein Feld, in das ich eine Auflagenzählung (1. Auflage, 2. korrigierte Auflage etc.) eingeben könnte. Diese Angabe brauchen wir aber dringend, sowohl für die Zitierempfehlung, die wir auf unseren Seiten ausgeben, als auch im Hinblick auf einen zukünftigen Export nach ONIX.

Im PKP-Github habe ich dazu ein Plugin gesehen:

pkp-lib/plugins/metadata/nlm30/tests/filter/sample-nlm23-citation.xml 

In OMP habe ich das Plugin NLM 3.0 meta-data gefunden. Könnet Ihr das für alle Imprints aktivieren (falls es das richtige ist)?

**Comment by ankosi** [comment]
@wit, @isgrim 

Habe leider noch keine Antwort auf dieses Issue bekommen. Ich habe wieder einen Titel, der in der 2. Auflage bei uns erscheint, Das NLM 3.0 meta-data-Plugin ist bei uns installiert und anscheinend aktiv geschaltet; der Bereich ist aber ausgegraut.
![screenhot5](https://user-images.githubusercontent.com/11088169/27391015-11c70238-56a3-11e7-89f6-e21abaa9d869.jpg)

**Comment by withanage** [comment]
@ankosi  sorry, ist etwas runtergagangen.
Es scheint ein standrd plugin zu sein, aber ob es stabil in der OMP Version , weiß ich nicht.
@isgrim könntest Du biite es  kurz mal schauen ?

**Comment by nils-stefan-weiher** [comment]
@ankosi 
Das einzige was ich jetzt von PKP dazu gefunden habe ist ein Beitrag im Forum wo sie über das Feature mit Editionen diskutieren:

http://forum.pkp.sfu.ca/t/forthcomings-preprints-new-editions-in-omp/5178

Ich weiß nicht woher diese NLM metadaten kommen ich habe bis jetzt kein Plugin gefunden bei dem man die Auflage einer Veröffentlichung eingeben kann.

Ich habe nochmal im PKP Forum nachgehakt, unter dem verlinkten Beitrag, und hoffe auf Antwort...
