### ISSUE TITLE
Erscheinungsdatum

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#11]
_From @kadowa on February 24, 2016 12:8_

Die Information "Veröffentlicht am" füllt sich aus dem ersten Feld, das in der Tabelle `date_published` gefunden wird. Allerdings kann eine Publikation mehrer Erscheinungsdaten haben (z.B. Print und Online), die jeweils ein individuelles Format haben können.

To do:
- [x] Unterscheiden zwischen Print- und Online-Datum (`role` abprüfen)
- [x] Format überprüfen (Print sollte YYYY, Online YYYYMMDD sein) und entsprechend ausgeben

:grey_exclamation: Bei den meisten Publikationen werden diese Felder erst sukzessive durch die Anwender befüllt, da die alte OMP-Katalogoberfläche als Veröffentlichungsdatum das Feld `date_submitted` verwendet.

_Copied from original issue: UB-Heidelberg/UBHD-OMPPropylaeum#6_

**Comment by kadowa** [comment]
Ergänzend:

> Am 25.02.2016 um 12:08 schrieb Anja Konopka:
> Liebe Maria,
> 
> ich fände es gut, auf beides hinzuweisen:
> 
> Online veröffentlicht am: (Datum der Online-Stellung)
> Erschienen am / erscheint als Buch am: (Datum der Printpublikation)
> 
> Liebe Grüße
> Anja
> 
> Am 25.02.2016 um 08:32 schrieb Dr. Katrin Bemmann:
> 
> > Liebe Maria,
> > 
> > ich fände das gut. Müsste aber von IT entsprechend programmiert werden.
> > Liebe Grüße
> > Katrin
> > 
> > Am 24.02.2016 um 22:46 schrieb Maria Effinger:
> > 
> > > Liebe Anja, liebe Katrin,
> > > sollte eigentlich auf dieser Überblicksseite nicht auch das Erscheinungsjahr (Erstveröffentlichungsdatum) ausgewiesen sein?
> > > http://heiup.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog
> > > http://heiup.uni-heidelberg.de/UBHD_OMPHeibooks/catalog
> > > 
> > > Liebe Grüße, Maria

**Comment by kadowa** [comment]
TO DO: Integration in alle Portale

**Comment by ankosi** [comment]
From @AnjaKonopka on March 2, 2016 16:36

Ausgabe von Erscheinungsjahr und ISBN der verschiedenen Publikationsformate in der linken Spalte unterhalb von "Empfohlene Zitierweise". Die empfohlene Zitierweise bezieht sich stets auf das PDF:

```
Empfohlene Zitierweise (PDF)

Nachname, Vorname: Titel:_Untertitel, Ort: Verlag, Jahr. doi:xx
```

### ISBN

Bei den ISBNs nennen wir alle vorhandenen, und zwar in der Form (unterhalb der CC-Lizenz):

9783946054016 (PDF) [vom Reiter PDF]
xxxx (Softcover) [-> vom Reiter Softcover]
xxxx (Hardcover) [-> vom Reiter Hardcover]
xxxx (Originalausgabe) [vom Reiter Originalausgabe]

### Erscheinungsdatum

Unterhalb von "Veröffentlicht am 23.07.2015" steht:

Erschienen als:
PDF yyyy [yyyy = Publication date vom Reiter PDF]
Softcover yyyy [yyyy = Date of publication vom Reiter Softcover]
Hardcover yyyy [yyyy = Date of publication vom Reiter Hardcover]

Die Originalausgabe erschien yyyy [= Date of first publication vom Reiter Originalausgabe] bei Verlagsname [= Verlagsname von diesem Reiter].

   Das Erscheinungsjahr des PDF ziehen wir vom Reiter PDF, dort ist es "Publication date".
    Das Erscheinungsjahr der Originalausgabe vom Reiter "Originalausgabe", dort wird auch die ISBN und der Verlag angegeben, als Bezug für das Datum wählen wir "Date of first publication"
    Das Erscheinungsjahr der PoD-Veröffentlichung von einem Reiter "Softcover" oder "Hardcover" (je nachdem, was es ist) aus dem Feld publication date. Auf diesem Reiter sollten wir ebenfalls ISBN und Verlag eingeben.

**Comment by kadowa** [comment]
Soll wirklich vor jeder ISBN "ISBN" stehen (evtl. zusätzlich zur Überschrift "ISBN")? Das führt bei mir schon bei Publikationsformaten mit kurzem Namen zu einem Zeilenumbruch (bei denen mit längerem wird sich der Umbruch nicht vermeiden lassen):

![isbn](https://cloud.githubusercontent.com/assets/8066366/14951704/6403e17c-105b-11e6-9c48-2a87c95e795a.png)

**Comment by kadowa** [comment]
Beim Erscheinungsdatum:
- Soll das Erscheinungsdatum des PDFs tatsächlich mehrfach aufgeführt werden?
- Ob das Erscheinungsdatum in der Vergangenheit oder in der Zukunft liegt, soll nicht mehr berücksichtigt werden?
- Bei der PoD-Veröffentlichung soll der Verlag angegeben werden, aber nicht angezeigt?

Hintergrund ist der: Je weniger vom Publikationsformatsname abhängt, desto besser. Regeln wie `Wenn Verlagsname vorhanden, gib aus 'erschienen bei <Verlagsname>'` sind leicht umzusetzen, Regeln wie `Wenn Name des Publikationsformats auf Deutsch = 'Originalveröffentlichung' überprüfe, ob Verlagsname vorhanden, falls ja, gib aus 'erschienen bei <Verlagsname>'` umständlicher und fehleranfälliger.

**Comment by ankosi** [comment]
Einmal ISBN als Überschrift reicht. Vor den Publikationsformaten reicht die Nummer.

**Comment by ankosi** [comment]
Erscheinungsdatum tatsächlich mehrfach aufführen, damit man sie unten alle im Blick hat. In der linken Spalte nur Angaben zu bereits erschienenen Büchern. Angabe zum geplanten Erscheinungstermin sollen auf der Katalogseite unterhalb des Abstracts stehen:
http://heiup.uni-heidelberg.de/catalog/index.html
Bei der PoD-Veröffentlichung soll der Verlag angegeben werden, aber nicht angezeigt? - Was meinst Du damit?

**Comment by kadowa** [comment]
Aber die mehrfach aufgeführten Erscheinungsdaten für das PDF stehen doch direkt untereinander, wenn wir das wie oben spezifiziert umsetzen?

Die Angabe des geplanten Erscheinungstermins auf der Katalogseite ist eine separate Anforderung und sollte in ein eigenes Issue.

Zu PoD steht oben:

> Das Erscheinungsjahr der PoD-Veröffentlichung von einem Reiter "Softcover" oder "Hardcover" (je nachdem, was es ist) aus dem Feld publication date. Auf diesem Reiter sollten wir ebenfalls ISBN und Verlag eingeben.

Zur Ausgabe:

> Softcover yyyy [yyyy = Date of publication vom Reiter Softcover]
> Hardcover yyyy [yyyy = Date of publication vom Reiter Hardcover]

Daraus habe ich geschlossen, dass der Verlag zwar im Feld Imprint bei Softcover und Hardcover angegeben wird, aber nicht – wie bei der Originalveröffentlichung – nach dem Erscheinungsdatum angezeigt werden soll. Besser wäre es tatsächlich, wenn der Verlag nicht angezeigt werden soll, diesen nicht anzugeben.

**Comment by ankosi** [comment]
**UPDATE Ausgabe von Erscheinungsjahr und ISBN**
@kadowa, @wwwubhd  
Die ISBN der verschiedenen Publikationsformate werden in der linken Spalte unterhalb von "Empfohlene Zitierweise" angegeben. Die empfohlene Zitierweise bezieht sich stets auf das PDF:

```
Empfohlene Zitierweise (PDF)

Nachname, Vorname: Titel:_Untertitel, Ort: Verlag, Jahr. doi:xx
```

### ISBN

Bei den ISBNs nennen wir alle, die sich auf unseren Verlag beziehen, und zwar in der Form (unterhalb der CC-Lizenz):

9783946054016 (PDF) [vom Reiter PDF]
xxxx (Softcover) [-> vom Reiter Softcover]
xxxx (Hardcover) [-> vom Reiter Hardcover]

Danach folgt:
"Veröffentlicht am 23.07.2015".

Danach ein dünner Strich (wie bei der Autorenbiographie).

Unterhalb des Striches steht eine Angabe, die nach folgendem Schema aufgebaut ist:

Die Originalausgabe erschien yyyy als zzzz [Publikationsformat angeben] bei XXXX [Verlagsname], ISBN XXX.

Die Angaben zur Orignalausgabe stammen aus dem Feld "Source" im "Catalog".

**Comment by kadowa** [comment]
So sähe es nach der neuen Spezifikation aus (der Text zur Originalausgabe ist nur ein Füller):

![quelle](https://cloud.githubusercontent.com/assets/8066366/15388346/c99f4f86-1db1-11e6-8176-7c51c129d265.png)

@AnjaKonopka, kommt das so hin? Mich stört der Trennstrich ein bisschen, weil er sich fast, aber nicht ganz, auf Höhe des Biographie-Trennstrichs befindet – @wwwubhd, was meint ihr als Webdesignexperten?

**Comment by ghost** [comment]
Zwei Trennstriche unausgerichtet nebeneinander wirkt tatsächlich etwas schief gestapelt, zumal da unten die Tabelle folgt, die ihrereseits nochmal massig Querlinien enthält. Da die Textfülle in den jew. Elementen von mal zu mal schwankt, wird es sich natürlich nicht einrichten lassen, dass die Trennstriche auf gleicher Höhe zu stehen kommen. Mich stört zudem, dass die Abstände über den Strichen größer sind als darunter. (Anna)

**Comment by ankosi** [comment]
Geht mir genauso. Ich würde es mal ohne Strich versuchen. Die  
Angaben zur Originalausgabe sind ja etwas nach unten abgesetzt, durch  
die Distanz wird schon angezeigt, dass eine neue Art Information kommt.

----- Nachricht von Katharina Wäschle notifications@github.com ---------
     Datum: Thu, 19 May 2016 02:11:43 -0700
       Von: Katharina Wäschle notifications@github.com
Antwort an: UB-Heidelberg/UBHD-OMPPortal  
reply@reply.github.com
   Betreff: Re: [UB-Heidelberg/UBHD-OMPPortal] Erscheinungsdatum (#11)
        An: UB-Heidelberg/UBHD-OMPPortal UBHD-OMPPortal@noreply.github.com
        Cc: AnjaKonopka konopka@ub.uni-heidelberg.de, Mention  
mention@noreply.github.com

> So sähe es nach der neuen Spezifikation aus (der Text zur  
> Originalausgabe ist nur ein Füller):
> 
>   [1]
> 
>   @AnjaKonopka[2], kommt das so hin? Mich stört der Trennstrich ein  
> bisschen, weil er sich fast, aber nicht ganz, auf Höhe des  
> Biographie-Trennstrichs befindet – @wwwubhd[3], was meint ihr als  
> Webdesignexperten?
> 
>   —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[4]
>       

----- Ende der Nachricht von Katharina Wäschle  
notifications@github.com -----

## Links:

[1]  
https://cloud.githubusercontent.com/assets/8066366/15388346/c99f4f86-1db1-11e6-8176-7c51c129d265.png
[2] https://github.com/AnjaKonopka
[3] https://github.com/wwwubhd
[4]  
https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/11#issuecomment-220269603
  Anja Konopka
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109, 69117 Heidelberg
Tel: +49 6221 542569
E-Mail: konopka@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de/

**Comment by kadowa** [comment]
@ankosi, @wwwubhd, final jetzt mit Strich: http://books.ub.uni-heidelberg.de/heibooks/catalog/book/66

**Comment by kadowa** [comment]
@Anna, Den Abstand über dem Strich habe ich in der grauen Box verkleinert.
