### ISSUE TITLE
Autoren/Herausgeber bei Sammelbänden

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#15]
_From @wwwubhd on February 9, 2016 13:41_

@kadowa 
Bei Sammelbänden sollen nur die Herausgeber, nicht aber die Autoren angezeigt werden.

_Copied from original issue: UB-Heidelberg/UBHD-OMPPropylaeum#4_

**Comment by kadowa** [comment]
_From @withanage on February 12, 2016 2:24_

@wwwubhd  falls nicht zu dringend ist, mache ich das.

**Comment by kadowa** [comment]
@wwwubhd, sollen Herausgeber in der Anzeige noch speziell gekennzeichnet werden, also z.B.

```
Editor A, Editor B (Hrsg.)
Titel
```

?

**Comment by kadowa** [comment]
_From @wwwubhd on March 8, 2016 9:20_

@kadowa @withanage 
Ja, bitte die Angabe hinzu fügen

**Comment by kadowa** [comment]
@AnjaKonopka, @wwwubhd könnt ihr bei Gelegenheit überprüfen, ob alles wie gewünscht angezeigt wird, bevor ich die Änderung in alle Portale übernehme?

**Comment by kadowa** [comment]
_From @wwwubhd on March 8, 2016 16:21_

Liebe Katharina,

danke!
http://heiup.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog/series/archber
sieht für mich sehr gut aus!
Nur bei Band 2 hat es den Autor verschluckt, aber der ist vielleicht 
nicht richtig eingegeben?
Viele Grüße, MAria

**Comment by kadowa** [comment]
_From @AnjaKonopka on March 8, 2016 16:38_

  Sieht prima aus! Danke, Katharina. Eine Sache wäre noch zu überlegen:

Maria, wollen wir - wenn es mehrere Herausgeber sind - dies an der
Abkürzung deutlich machen: Hrsgg.??

**Comment by kadowa** [comment]
_From @AnjaKonopka on March 16, 2016 9:0_

@kadowa, Wenn mehr als drei Herausgeber oder Autoren angegeben sind, sollen die ersten drei aufgeführt werden, nach dem dritten soll  "et al." stehen:

Bei mehr als drei Autoren also:
Vorname Nachname, Vorname Nachname, Vorname Nachname et al.

Bei mehr als drei Herausgebern:
Vorname Nachname, Vorname Nachname, Vorname Nachname et al. (Hrsg)

**Comment by ankosi** [comment]
Die Angabe "et al" fehlt bisher noch, und es werden auch mehr als drei Autoren/Herausgeber angezeigt, z. B. hier:
http://heiup.uni-heidelberg.de/UBHD_OMPHeibooks/catalog/book/62

Bei folgenden Titeln habe ich et. al. vorläufig händisch eingefügt:
https://books.ub.uni-heidelberg.de/index.php/heibooks/catalog/book/73
https://books.ub.uni-heidelberg.de/index.php/heibooks/catalog/book/71
https://books.ub.uni-heidelberg.de/index.php/heibooks/catalog/book/62

**Comment by ankosi** [comment]
Wenn dieses Issue erledigt ist und geschlossen wird, bitte mir zuweisen, damit ich die  Daten in OMP korrigiere.

**Comment by kadowa** [comment]
@AnjaKonopka, entsprechende Änderungen sind jetzt in der Testinstanz. Bitte überprüfe nach Korrektur der Daten erstmal dort (z.B. http://books.ub.uni-heidelberg.de/UBHD_OMPHeibooks/catalog/book/62), ob alles richtig angezeigt wird, bevor wir die Änderungen in die Produktivinstanz übernehmen. Bitte auch die Katalog- und Serienübersichtsseiten kontrollieren, dort habe ich die Änderungen analog übernommen.

**Comment by ankosi** [comment]
Sieht gut aus. Bitte so in die Produktivinstanz übernehmen.
