### ISSUE TITLE
Produktivinstanz xAsia

### ISSUE THREAD

**Issue by nidame** [UB-Heidelberg/UBHD-OMPPortal#18]
xAsia ist bisher nur Testinstanz und sollte in Produktivinstanz überführt werden mit Verknüpfung zum Backend. Zur Zeit werden Dummy-Inhalte aus Propylaeum geladen.

**Comment by kadowa** [comment]
Eine Produktivinstanz http://heiup.uni-heidelberg.de/xasia ist jetzt live.

**Comment by withanage** [comment]
@nidame  Gibt es da noch Änderungs-bedarf ?

**Comment by nidame** [comment]
Ja, ein paar Dinge passen noch nicht
- im Tab oben steht arthistoricum.net (s. Screen_1)
- es werden nur Band 2 u. 3 der Reihe angezeigt, obwohl Bd. 1 schon hochgeladen ist
- Verlagsangaben stimmen nicht, Ort nicht angezeigt (s. Screen_2)
- Jahr der Erstveröffentlichung nicht korrekt angezeigt (s. Screen_3)
  ![screen_1](https://cloud.githubusercontent.com/assets/17901102/14022114/b467451e-f1de-11e5-9a6f-7b42621c1450.png)
  ![screen_2](https://cloud.githubusercontent.com/assets/17901102/14022117/b6695de8-f1de-11e5-9a22-4a21cb8c5b2e.png)
  ![screen_3](https://cloud.githubusercontent.com/assets/17901102/14022122/bc79b70a-f1de-11e5-8c94-2fc46b148d6c.png)

**Comment by withanage** [comment]
@nidame  meinte wegen der domain  weiterleitungen, damit dieses Ticekt  zu schließen.
ich würde für einzelne Probleme einzelne Tickets öffnen,

**Comment by nidame** [comment]
**@withanage** ok verstehe. dann gibt es aus meiner Sicht keinen Änderungsbedarf mehr
