### ISSUE TITLE
commits gehen nicht durch

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPortal#19]
@withanage @isgrim @kadowa 

Folgendes Problem:
ich habe an einigen Seiten (die fett markierten) in Arthistoricum etwas geändert. Beim Commit kam folgende Fehlermeldung:
error: unable to unlink old '**views/partner/dbae.html**' (Keine Berechtigung)

Ich habe daraufhin versucht, das ganze zu erzwingen. Dann habe ich aber folgende Fehlermeldung erhalten:
error: Your local changes to the following files would be overwritten by merge:
    **views/about_us/profile.html
    views/home/index.html
    views/series/dbae_info.html
    views/series/eva_info.html
    views/series/vmps_info.html**
Please, commit your changes or stash them before you can merge.

Beide Fehlermeldung habe ich gestern auch schon erhalten. Ich weiß, dass die zweite Fehlermeldung eigentlich nur dann auftreten soll, wenn jemand etwas in der Produktivinstanz direkt geändert hat. Das habe ich aber nicht und ich wüsste auch sonst niemanden, der das getan haben soll und schon gar nicht zufälligerweise an genau den Dateien, die ich gerade bearbeitet habe. Es muss also irgendetwas beim Commit schief gehen. Könntet ihr da mal schauen und schnell beheben?

Viele Grüße
Daniela

**Comment by withanage** [comment]
@wwwubhd 
Du hattest keine Änderungen in produktivem instanz oder ?
dann werde ich in dem produktiven instanz 
cd   produktiven ordner
git checkout views/about_us/profile.html views/home/index.html  views/series/dbae_info.html usw. machen und
 ./put_into_git_arthistoricum.sh
skript anstoßen

**Comment by ghost** [comment]
@withanage 
Nein, wie ich schon geschrieben habe, habe ich nichts in der Produktivinstanz gemacht. Trotzdem taucht dieser Fehler wieder und wieder auf. Es wäre eben schön, wenn sich dafür eine dauerhafte Lösung finden würde, denn ich habe den Eindruck, dass durch das checkout bestimmte Änderungen nicht übernommen werden.

**Comment by withanage** [comment]
@wwwubhd 
habe eine zusätzliche Befehl im Skript eingebaut.
Bitte testen und gegebenfalls melden oder das Ticket schließen.

**Comment by ghost** [comment]
Ich habe es ausgetestet und bekam keine Fehlermeldung mehr zurück. Allerdings lässt sich die Produktivinstanz nun nicht mehr ansteuern. Der Browser gibt folgenden Fehler zurück:
The requested URL /admin/default/ticket/arthistoricum/147.142.85.97.2016-03-22.14-18-35.965aea6e-45ed-4343-848f-6a493126ca8e was not found on this server.

**Comment by withanage** [comment]
läuft jetzt. 
es soll immer ./put_into_git_arthistoricum.sh aufegührt werden. auch wenn keine änderugen da sind.
dann wird settings file kopiert, daher war der error

**Comment by ghost** [comment]
Danke. Aber ich habe immer ./put_into_git ausgeführt. Ich kann mir nicht erklären, woher der Fehler kommen soll.
