### ISSUE TITLE
Herausgeber der Reihe anzeigen

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#20]
@isgrim @kadowa 

Bei Reihen wie dieser:

http://heiup.uni-heidelberg.de/UBHD_OMPHeibooks/series

ist in OMP ein Reihenherausgeber hinterlegt, der im Frontend allerdings nicht angezeigt wird. Bitte den Reihenherausgeber auf der dynamisch erzeugten Übersichtsseite unterhalb des Reihentitels anzeigen, etwas abgesetzt und in kleinerer Schriftgröße, eingeleitet mit:

Herausgeber:

Dieses Issue gilt für alle Plattformen.

**Comment by nils-stefan-weiher** [comment]
Dazu muss das interne Datenbankschema in den Portalen noch erweitert werden, da die Informationen zu dem Reihenherausgebern aus den Benutzerdaten kommt.
Das kostet etwas mehr Aufwand und dazu müssen wir uns in der Entwicklung nochmal absprechen.

**Comment by withanage** [comment]
@wwwubhd   @AnjaKonopka 
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/series/hst.html
die Menu nicht verlinkt ist: 
Sollte das weiterhin manuell gepflegt werden oder braucht man diese Funktion für heiup nicht, da noch keine Serien gibt ?
dann können wir heiup als label raus-bringen.

**Comment by nils-stefan-weiher** [comment]
Für heibooks implementiert:
http://heiup.uni-heidelberg.de/UBHD_OMPHeibooks/series
@wwwubhd 
Ist das Layout so wie gewünscht?
Wenn ja, dann würde ich das für die anderen Portale (propylaeum, xasia, arthistoricum) auch so übernehmen.

**Comment by ghost** [comment]
@AnjaKonopka Ich gebe die Frage mal an dich weiter: Bist du mit dem Aussehen so jetzt zufrieden?

**Comment by ankosi** [comment]
Danke, ja so ist es gewünscht und kann gerne für die anderen Portale so übernommen werden.
@wwwubhd: Einverstanden?

**Comment by ghost** [comment]
Ja, von unserer Seite her gibt es keine Einwände

**Comment by ghost** [comment]
@withanage 
@AnjaKonopka
_Zum Problem: 
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/series/hst.html
die Menu nicht verlinkt ist:
Sollte das weiterhin manuell gepflegt werden oder braucht man diese Funktion für heiup nicht, da noch keine Serien gibt ?
dann können wir heiup als label raus-bringen._
Ja, genau - weil es noch keine Reihen gibt - evtl. passiert Ende April etwas an dieser Front, dann soll die Funktion freigegeben werden, aber vorher muss das mit dem Cluster besprochen werden.

**Comment by ankosi** [comment]
@kadowa Sollen die Reihenherausgeber für diese Reihe in OMP angelegt werden?

**Comment by kadowa** [comment]
Noch sind diese Änderungen nur in Arthistoricum zum Testen. Schaden kann es aber nichts, den Herausgeber schon mal anzulegen.
