### ISSUE TITLE
Bitte Arthistoricum freischalten

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPortal#21]
@withanage 

Wie besprochen :-D

**Comment by withanage** [comment]
@wwwubhd 
http://books.ub.uni-heidelberg.de/arthistoricum/
war schon weitergeleitet.

Nur habe ich die https blockiert.

Reicht das so  ?

https://books.ub.uni-heidelberg.de/index.php/arthistoricum

**Comment by withanage** [comment]
@wwwubhd  ok. werde ich das das Ticket schließen.
Gegebenfalls bitte melden.
