### ISSUE TITLE
DOI wird nicht bei allen Titeln angezeigt

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPortal#22]
@withanage @AnjaKonopka @bettinamueller 
Bei Arthistoricum wird die DOI nicht bei allen Titeln angezeigt. Beim Model ist sie z.B. zu sehen.

**Comment by kadowa** [comment]
@wwwubhd, interessant wäre vor allem, wo sie _nicht_ zu sehen ist, aber angezeigt werden sollte. Link?

**Comment by ghost** [comment]
@kadowa 
Hier ein paar Beispiele:
http://books.ub.uni-heidelberg.de/arthistoricum/catalog/book/76
http://books.ub.uni-heidelberg.de/arthistoricum/catalog/book/31
http://books.ub.uni-heidelberg.de/arthistoricum/catalog/book/30
http://books.ub.uni-heidelberg.de/arthistoricum/catalog/book/29

**Comment by kadowa** [comment]
Ok, scheint wieder ein Lokalisierungsproblem zu sein. Mit englischer Spracheinstellung werden sie angezeigt:

http://books.ub.uni-heidelberg.de/arthistoricum/catalog/book/76?lang=en

Ich arbeite dran ...

**Comment by kadowa** [comment]
Sollte sich mit https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/3 lösen lassen.

**Comment by ghost** [comment]
@kadowa @AnjaKonopka 
Ich habe jetzt noch zu diesem Thema einen weiteren Aspekt aufgetan: kann es sein, dass die DOI erst ein ganzes Stück nach Veröffentlichung des Buches richtig erzeugt wird? Ich hatte jetzt mehrmals den Hinweis bei bereits veröffentlichten Bänden, dass die DOI nur vorläufig erzeugt ist und die richtige erscheint, wenn das Buch veröffentlicht ist. Anja und ich haben uns das jetzt lange angesehen und nichts gefunden, was falsch eingetragen worden wäre (zumindest nichts, was für die DOI wichtig ist), aber plötzlich war der Hinweis dann weg und die DOI tauchte auf dem Frontend auf.

**Comment by kadowa** [comment]
Eigentlich wird die DOI genau in dem Moment erzeugt, in dem der Katalogeintrag veröffentlich wird. Bei welchem Band taucht die DOI jetzt korrekt auf? Bei mir werden die oben gelisteten weiterhin nur auf der englischen Seite angezeigt.

**Comment by ghost** [comment]
Hier zum Beispiel: http://books.ub.uni-heidelberg.de/arthistoricum/catalog/book/86

**Comment by kadowa** [comment]
Da taucht die DOI bei mir auch nur auf, wenn ich die Spracheinstellung auf "EN" setze. Screenshot?

**Comment by kadowa** [comment]
Zur Ursache s. #47.
