### ISSUE TITLE
oastatistik brauacht   keine  volles-json  bei jede abfrage, nur das von einzelne kapitel 

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#23]

**Comment by withanage** [comment]
in portal  einebaut und zum testen frei-gegeben.

**Comment by ankosi** [comment]
Wo kann ich testen? Auf der heiBOOKS-Testseite?

Am 04.04.2016 um 11:27 schrieb Dulip Withanage:

> in portal einebaut und zum testen frei-gegeben.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/23#issuecomment-205210412

## 

Anja Konopka
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109
69117 Heidelberg

Tel: +49 (0)6221 542569
Fax: +49 (0)6221 542623

E-Mail: konopka@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de

**Comment by withanage** [comment]
@AnjaKonopka  die Änderung habe ich   für Florian gemacht.
Aber trotzdem
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/api/oastatistik?repo=omphp&type=json&ids=43-231-xml,43-230-pdf,43-218-pdf,43-217-xml
Auf #25  komme ich noch  ;-)

**Comment by withanage** [comment]
fertig.
