### ISSUE TITLE
Statistikanzeige funktioniert noch nicht

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#25]
@withanage, @isgrim, @wwwubhd 

In heiBOOKS zeigt die Statistikanzeige noch keine Werte an, z. B. hier:
http://books.ub.uni-heidelberg.de/heibooks/catalog/book/61

**Comment by withanage** [comment]
@AnjaKonopka 
@wwwubhd 

Statistik anzeige in heibooks und in arthistoricum eingebaut. Bitte testen.

**Comment by ankosi** [comment]
Die angezeigten Zahlen auf heibooks sehen ganz plausibel aus. Allerdings ändert sich der Wert nicht, wenn ich eine Datei downloade.

**Comment by withanage** [comment]
@AnjaKonopka 
die werte werde immer  erst nach paar Tagen gezählt , da sie  erst in Göttingen ausgewertet werden. Wann es aktualisiert wird habe ich keinen Einfluss
