### ISSUE TITLE
PNG-Covers werden nicht angezeigt

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#26]
@wwwubhd

**Comment by withanage** [comment]
@kadowa
Bitte checken, ob diese Funktionalität  in alle Portale da sind. Wenn nicht bitte mergen.

**Comment by kadowa** [comment]
- [x] arthistoricum
- [x] propylaeum
- [x] heibooks
- [x] heiup
- [x] xasia
