### ISSUE TITLE
Lizens Typ Darstellung

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#27]

**Comment by kadowa** [comment]
Gibt es hierfür eine Spezifikation?

**Comment by ankosi** [comment]
Nein :-(

Am 13.06.2016 um 13:08 schrieb Katharina Wäschle:

> Gibt es hierfür eine Spezifikation?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/27#issuecomment-225552037, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AKkxKYYN-siaHYw_BP_kkpM89rX6qoFyks5qLTpJgaJpZM4ICE7X.

## 

Anja Konopka
Abteilung Publikationsdienste
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109
69117 Heidelberg

Tel: +49 (0)6221 542569
Fax: +49 (0)6221 542623

E-Mail: konopka@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de

**Comment by withanage** [comment]
@ankosi
 wäre gut, dass es genauer  spezifiziert  wird, was ausgegeben werden muss. OMP  Backend hat das Feld "Lizens URL".   Das könnte für unterschiedliche Lizens-typen eingegeben werden. Anhand dieser Information könnte das Text, ausgegeben werden. 
![screenshot from 2016-06-17 11 30 42](https://cloud.githubusercontent.com/assets/1921992/16146561/fc3a7ea0-347e-11e6-97bc-6ab762ca01a9.png)

Welche  Lizensen außer cc-by  werden noch verwendet ?

**Comment by kadowa** [comment]
This issue was moved to kadowa/UBHD-OMPPortal#1
