### ISSUE TITLE
Reihensortierung in alphabetischer Reihenfolge

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#28]
S. https://github.com/UB-Heidelberg/UBHD-OMPPropylaeum/issues/11

**Comment by nils-stefan-weiher** [comment]
Für heibooks angepasst.

https://github.com/UB-Heidelberg/UBHD-OMPHeibooks/commit/394867b341cbc3391d403a69e146d978409ecdde
