### ISSUE TITLE
ISBN und Veröffentlichungsdatum aus allen Publikationsformaten

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#31]
http://books.ub.uni-heidelberg.de/propylaeum/catalog/book/22

   Anja und ich haben hier gerade den PoD-Button aktiviert, aber leider wird er im Frontend nicht sichtbar.
   Es ist nur die Hardcover ISBN aber nicht die ISBN des PDFs sichtbar.
   Das Veröffentlichungsdatum des Hardcovers wird nicht angezeigt.

**Comment by kadowa** [comment]
Gilt vermutlich für alle Portale, oder?

**Comment by ankosi** [comment]
Das Problem begegnet mir bei Propylaeum zum ersten Mal. Wir haben hier aber auch zum ersten Mal das Publikationsformat Hardcover angelegt.

**Comment by kadowa** [comment]
So korrekt? http://books.ub.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog/book/22

**Comment by ankosi** [comment]
Im Prinzip ja, danke! Falls die Frage sich auch auf die Formalia 
bezieht: Zwischen den ISBN-Angaben bitte einen etwas kleineren Abstand. 
Wie wir das Erscheinungsdatum zeigen, besprechen wir ja separat.
