### ISSUE TITLE
dois umziehen

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#33]
serverseitig dois umleiten.

**Comment by withanage** [comment]
@wwwubhd  Daniela bitte testen
http://dx.doi.org/10.11588/heibooks.70.60

**Comment by ghost** [comment]
@withanage Bei heibooks geht es nun, bitte auch für Arthistoricum umsetzen

**Comment by withanage** [comment]
@wwwubhd  
gemacht, bitte testen

**Comment by ghost** [comment]
@withanage Danke, sieht jetzt auch gut aus

**Comment by withanage** [comment]
@wwwubhd  ok.
dann werde ich  nur Verwaltung link einschalten und  das ticket schließen.

**Comment by kadowa** [comment]
Was ist denn mit den übrigen Portalen? Gibt es da das Problem nicht? Nicht, dass wir das Issue in ein paar Wochen wieder aufmachen müssen ...

**Comment by withanage** [comment]
Das hängt  von wie man sich DOIS für andere Portale anmeldet. Ist serverseitig.
Geht ohne ticket

**Comment by ankosi** [comment]
-Doch, klar, gilt für alle Portale.Das doi-Problem ist ja überall das Gleiche.

Morgen klappt es wahrscheinlich mit dem OMP-Anwendertrffen. Ich komme  
wahrscheinlich zum Treffen und fahre dann heim.

LG
Anja

---- Nachricht von Katharina Wäschle notifications@github.com ---------
      Datum: Tue, 12 Apr 2016 06:37:56 -0700
        Von: Katharina Wäschle notifications@github.com
Antwort an: UB-Heidelberg/UBHD-OMPPortal  
reply@reply.github.com
    Betreff: Re: [UB-Heidelberg/UBHD-OMPPortal] dois umziehen (#33)
         An: UB-Heidelberg/UBHD-OMPPortal UBHD-OMPPortal@noreply.github.com

> Was ist denn mit den übrigen Portalen? Gibt es da das Problem nicht?  
> Nicht, dass wir das Issue in ein paar Wochen wieder aufmachen müssen  
> ...
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/33#issuecomment-208909042

----- Ende der Nachricht von Katharina Wäschle  
notifications@github.com -----

Anja Konopka
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109, 69117 Heidelberg
Tel: +49 6221 542569
E-Mail: konopka@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de/

**Comment by ghost** [comment]
Für Propylaeum kann man es auf jeden Fall auch schon einrichten. Bei Crossasia sind noch keine DOIs registriert.
