### ISSUE TITLE
Button umbenennen

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#34]
(@wwwubhd zur Kenntnis)
Bitte auf allen Plattformen "Print on Demand" umbenennen in "Buch kaufen"

**Comment by kadowa** [comment]
Wie soll der Button in der englischen Übersetzung heißen?

**Comment by ankosi** [comment]
Purchase

**Comment by kadowa** [comment]
Bsp.: http://books.ub.uni-heidelberg.de/UBHD_OMPHeibooks/catalog/book/70

**Comment by ankosi** [comment]
Sieht gut aus!
