### ISSUE TITLE
Formatierung Abstract in Reihenübersicht

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#35]
Durch verschiedene Änderungen an der Reihenübersichtsseite ragt der Abstract-Text jetzt über die vorgesehene Position hinaus (vgl. http://books.ub.uni-heidelberg.de/UBHD_OMPArthistoricum/series und http://books.ub.uni-heidelberg.de/arthistoricum/series); bitte korrigieren.

![arthistoricum_reihen](https://cloud.githubusercontent.com/assets/8066366/14777362/e0de6fee-0acc-11e6-8b7c-9015e3b9090b.png)

**Comment by ghost** [comment]
@kadowa: Das Problem ist behoben
