### ISSUE TITLE
Formatierung Kapitelanzeige

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#36]
Kapitelanzeige entsprechend der Spezifikation formatieren (Beispiel: http://books.ub.uni-heidelberg.de/UBHD_OMPArthistoricum/catalog/book/49).

![arthistoricum_kapitel](https://cloud.githubusercontent.com/assets/8066366/14777446/5848e56e-0acd-11e6-9b31-a972f312f27b.png)

**Comment by ghost** [comment]
Die neue Formatierung kann nun im Testsystem angesehen werden.
