### ISSUE TITLE
OA-Statistik anpassen und aktivieren

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#37]
Die OA-Statistik ist mit https://github.com/UB-Heidelberg/UBHD-OMPArthistoricum/commit/f70b77597b5074357ddbe48f9a1dbee678b3146e deaktiviert. Bitte an den neuen Code zur Generierung der Downloadfiles anpassen und wieder aktivieren.

**Comment by withanage** [comment]
@kadowa kannst du mir in ompdal.py eine Funktion schreiben für ein monographie das "volle PDF" oder "volle XML"  ID liefert. 
z.B. geFullFileID(submission_id, type)

Dann kann ich die javascript anpassen und dann fehlt nichts für den umzug auf das neue   Repo für web2py_modules oder ?

**Comment by kadowa** [comment]
@withanage, eventuell gibt es schon alles, was du brauchst: Du kannst mit `getPublicationFormatByName(self, submission_id, name, available=True, approved=True)` (s. [Code](https://github.com/UB-Heidelberg/UBHD-OMPArthistoricum/blob/master/modules/ompdal.py#L338-L351)) dir das Publikationsformat mit dem entsprechenden Namen holen und dann darüber die Datei mit `getLatestRevisionOfFullBookFileByPublicationFormat(self, submission_id, publication_format_id)` (s. [Code](https://github.com/UB-Heidelberg/UBHD-OMPArthistoricum/blob/master/modules/ompdal.py#L380-L397)). Sähe dann vermutlich so aus:

```
pdf = ompdal.getPublicationFormatByName(submission_id, "XML")
pdf_file = ompdal.getLatestRevisionOfFullBookFileByPublicationFormat(submission_id, pdf.publication_format_id)
```

Ja, wenn die Statistik angepasst ist, kann ich die Änderungen mergen und die Repos umbauen. Zurzeit ist der Stand so: In arthistoricum sind die Änderungen im master-Branch, bei propylaeum, heibooks und xasia im spring-clean-Branch, der momentan nur in der Testinstanz ausgecheckt ist. Du müsstest dann deine Änderungen entsprechend dort committen.
