### ISSUE TITLE
3. Ebene in heiUP?

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPortal#38]
Soweit ich weiß, ist es in heiUP nicht möglich, eine dritte Ebene anzulegen. Dulip hatte mir im Januar gezeigt, dass man das emulieren kann, wenn man den Inhalt parametrisiert in ein div auf der "darüber liegenden" Seite einträgt. 
(http://heiup.uni-heidelberg.de/UBHD_OMPPortal/campusmedia/ruperto_carola/contact)
Ich werde heute/morgen analog die Serien-Seiten "anlegen".
Bleibt das auch langfristig bei dieser Lösung? 
Und gilt das für alle unsere Bootstrap-Oberflächen?

**Comment by kadowa** [comment]
Das muss ich mir mal noch genauer ansehen – prinzipiell ist es so, dass man die Hierarchie ab der dritten Ebene über Parameter löst. Verstehe ich das richtig, dass es darum geht, unter campusmedia eine Serienseite anzulegen? Oder geht es um die Serien-Infoseiten, über die wir gestern gesprochen hatten?

**Comment by ghost** [comment]
Aktuell geht es um die Serien-Info-Seiten - die Campusmedia-Kontaktseite gibt es bereits, die habe ich im Januar angelegt, die war jetzt nur Bsp. für die Lösung, die Dulip seinerzeit eingerichtet hatte...

**Comment by kadowa** [comment]
Dann so wie bisher bei den Serien; wenn heiUP in naher oder ferner Zukunft auch der Aufräumkur unterzogen wird, stelle ich das dann um.
