### ISSUE TITLE
Verlagsnamen im Wiki aktualisieren

### ISSUE THREAD

**Issue by bettinamueller** [UB-Heidelberg/UBHD-OMPPortal#39]
Bitte Verlagsnamen im Wiki aktualisieren. Noch sind die alten Namen drin:
- Heidelberg University Publishing
- heiBOOKS
- Propylaeum-eBooks
- arthistoricum.net-ART-Books
- CrossAsia eBooks 

@AnjaKonopka, könntest du das bei Gelegenheit machen?

**Comment by ankosi** [comment]
Geändert in
- Heidelberg University Publishing
- heiBOOKS
- Propylaeum
- arthistoricum
- CrossAsia https://heidi.ub.uni-heidelberg.de/ubwiki/CrossAsia
  eBooks (noch nicht endgültig geklärt)

**Comment by ghost** [comment]
@AnjaKonopka 
Da bin ich gerade etwas verwirrt. Von Arthistoricum z.B. ist doch der Verlagsnahme arthistoricum.net-Artb-Books, oder täusche ich mich da?
Und bei Propylaeum ist es auch nicht nur "Propylaeum". Oder ist damit etwas anderes gemeint, als ich gerade denke?

**Comment by ankosi** [comment]
Gemeint ist, wie der Verlagsname in OMP einzugeben ist, damit er nachher 
unseren Websites bei der empfohlenen Zitierweise richtig erscheint. Hier 
habe ich den Verlagsnamen in Übereinstimmung mit dem, wie wir auch an 
die ISBN-Agentur gemeldet haben, angegeben.
