### ISSUE TITLE
Kurzbiografien- Ausgabe mehrerer Kurzbiografien als nur einer

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#4]
_From @AnjaKonopka on March 7, 2016 17:24_

Zur Zeit wird nur eine (vermutlich die erste) Kurzbiografie auf dem Frontend ausgegeben. Wir haben - vor allem bei Sammelbänden - aber meist mehrere Autoren oder Herausgeber. Bitte möglichst die Ausgabe von drei Kurzbiografien ermöglichen.

_Copied from original issue: UB-Heidelberg/UBHD-OMPHeibooks#5_

**Comment by kadowa** [comment]
@AnjaKonopka, hier bräuchten wir noch eine genauere Spezifikation, wie mehrere Kurzbiographien ausgegeben werden sollen.
- Gilt #5 noch?
- Wie sollen die einzelnen Biographien voneinander abgesetzt werden – Leerzeile, Überschrift, Trennlinie o.ä.?
- Bei Sammelbänden: Nur die Biographien der Herausgeber anzeigen und Biographien der Autoren – falls vorhanden – ignorieren?
- Sollen immer nur maximal drei Biographien ausgegeben werden? Nach welchem Kriterium sollen diese ausgewählt werden? _author_seq_? Die Reihenfolge, in der die Autoren angelegt wurden?

**Comment by kadowa** [comment]
- Bei der Anmoderation (#5) sollte vermutlich zwischen einer und mehrerer Autorbiographien unterscheiden werden, oder?

**Comment by ankosi** [comment]
- Biographien absetzen mit Leerzeile, Name des Autors/Herausgebers: fett, auf neuer Zeile die Biographie.
- Auf Gesamtbuchebene bei Sammelbänden nur die Biographien der Herausgeber zeigen. Bei Werken mehrerer Autoren ohne Herausgeber nur dann Biographien der Autoren zeigen, wenn es insgesamt nicht mehr als drei Autoren gibt.
- Sammelbiographien werden wir nicht mehr zugelassen, da wir ggfs. später die Biographien über einen Link zum Autor auf einer seperaten Seite anzeigen lassen (das aber erst viel später)
- bei Anmoderation zwischen einer und mehreren Autorenbiographien unterscheiden
- Unterscheidung Frau/Mann: In OMP kann bei im Catalog -> Entry -> Contributor beim Contributor "Add user" anklicken und dadurch einen Eintrag als Benutzer anlegen und dort auch das Geschlecht angeben. Darüber könnte man auch das Geschlecht festlegen. Was hältst Du von dieser Vorgehensweise? Ich habe es mal ausprobiert bei der ersten Hrsg. von heiBOOKS ID 73.

**Comment by kadowa** [comment]
Das Geschlecht ist dann aber nur beim User hinterlegt, oder? Dann halte ich das für schwierig, an die Information wieder heranzukommen, da zwischen User und Autor keine Verbindung besteht abgesehen vom identischen Namen (der ja auch im Nachhinein geändert werden kann).

**Comment by ankosi** [comment]
Ja, das Geschlecht ist dann nur beim User hinterlegt.

----- Nachricht von Katharina Wäschle notifications@github.com ---------
     Datum: Tue, 19 Apr 2016 01:21:28 -0700
       Von: Katharina Wäschle notifications@github.com
Antwort an: UB-Heidelberg/UBHD-OMPPortal  
reply@reply.github.com
   Betreff: Re: [UB-Heidelberg/UBHD-OMPPortal] Kurzbiografien- Ausgabe  
mehrerer Kurzbiografien als nur einer (#4)
        An: UB-Heidelberg/UBHD-OMPPortal UBHD-OMPPortal@noreply.github.com
        Cc: AnjaKonopka konopka@ub.uni-heidelberg.de

> Das Geschlecht ist dann aber nur beim User hinterlegt, oder? Dann  
> halte ich das für schwierig, an die Information wieder  
> heranzukommen, da zwischen User und Autor keine Verbindung besteht  
> abgesehen vom identischen Namen (der ja auch im Nachhinein geändert  
> werden kann).
> 
>   —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[1]
>       

----- Ende der Nachricht von Katharina Wäschle  
notifications@github.com -----

## Links:

[1]  
https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/4#issuecomment-211790342
  Anja Konopka
Heidelberg University Publishing
Universitätsbibliothek Heidelberg
Plöck 107-109, 69117 Heidelberg
Tel: +49 6221 542569
E-Mail: konopka@ub.uni-heidelberg.de

http://heiup.uni-heidelberg.de
http://www.ub.uni-heidelberg.de/

**Comment by kadowa** [comment]
:grey_exclamation: Update:
- [x] Anmoderation entfernen
- [ ] Biographien mit Trennstrich absetzen (@wwwubhd)
