### ISSUE TITLE
Eigene 404

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#40]
@withanage, @isgrim, sollten wir uns eine eigene, an das Design angepasste 404-Seite zulegen, z.B. für nicht existierene Submissions-, Reihen-, Partnerseiten usw.? Momentan leiten wir in solchen Fällen immer auf die Startseite um.

**Comment by withanage** [comment]
@kadowa 
finde gut, falls wir eine formatierte static/404.html hätten, mit geeignetem Fehlermeldung , Navigations-Leiste und  nachher mit der integrierten Suche.

wie z.B 
http://www.uni-heidelberg.de/universitaet/123

Aber ich denke die Nutzer können sich entscheiden, ob sie es so wollen oder nicht.
Würde in Anwendung- treffen fragen.

**Comment by nils-stefan-weiher** [comment]
Bin auch dafür eine eigene zu machen, automatische Umleitung ohne Meldung ist nicht so sinnvoll, weil dann dem Besucher nicht klar ist, dass die Adresse nicht existiert.

**Comment by kadowa** [comment]
This issue was moved to kadowa/UBHD-OMPPortal#2
