### ISSUE TITLE
t_usage_statistics

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#41]
Wird die Tabelle `t_usage_statistics` noch genutzt? Hier passiert nichts:

https://github.com/UB-Heidelberg/UBHD-OMPPortal/blob/master/views/layout.html#L339-L340

Der letzte Eintrag hat den timestamp `2015-07-28 20:45:21`.

**Comment by kadowa** [comment]
Hintergrund: Wenn die OMP-Portale kein INSERT auf der OMP-Datenbank ausführen, könnten wir von außen mit einem Account, der nur Leserechte hat, auf die Datenbank zugreifen und uns so die regelmäßigen Dumps sparen.

**Comment by withanage** [comment]
ja. die tabelle brauche ich für statistiks. inserts sollten auch regelmässig passieren.

**Comment by kadowa** [comment]
Dann würde ich einen Config-Parameter `enable_usage_statistics` einführen, damit sich das für die lokalen Entwicklerinstanzen abschalten lässt. Ok?

**Comment by withanage** [comment]
ja, perfect.

**Comment by withanage** [comment]
übrigens, nirgendwo bitte ausschalten. 
ich werde  diese tabelle noch aufbauen, da unsere externe oastatistik  einige daten nicht liefern und ich werde da noch session info usw. aufbauen und versuchen  eine counter-compatibilität algorithmus einzuführen.
