### ISSUE TITLE
Downloadtabelle

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#42]
Hier passieren unschöne Dinge mit der Downloadtabelle. Eventuell liegt es an den langen Kapitelnamen?

http://books.ub.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog/book/53

![tabelle_doppeladler](https://cloud.githubusercontent.com/assets/8066366/15011620/2a197ec4-11f3-11e6-8894-02e2fbb33d69.png)

**Comment by kadowa** [comment]
@wwwubhd, seid ihr hier schon weiter gekommen?

**Comment by kadowa** [comment]
@withanage, könntest du dir das Problem mal anschauen?

**Comment by withanage** [comment]
@kadowa  das ist die css formatierung. 
Das div id downloadTable überschreibt css werte. 
Sollte css downloadTable richtig formatieren. Vermute mal die übreschrieben ist.
@wwwubhd  könnte dir da mit css am besten helfen.

**Comment by ghost** [comment]
@withanage @kadowa  Als ich geschaut habe, lag das Problem in der Ausgabe der div-Verschachtelung; letztere lässt sich mit CSS nicht beeinflussen: Bei Propylaeum wird die Tabelle im div class="widget" ausgegeben, das nach div class="col-lg-9" ausgegeben wird.
In Arthistoricum wird innerhalb des col-lg-9 ausgegeben.
Im Inspektor sehen die Anweisungen für die Styles für div downloadTable gleich aus.
Ist die CSS-Priorisierung bei PropylaeumBooks anders als bei ArthistoricumBooks?

**Comment by withanage** [comment]
@wwwubhd : sollte die gleiche Reihenfolge css sein , habe  eins zu eins kopiert damals.
Ob nachher was geändert hat, weiß ich nicht. 

ich habe testweise  div id gelöscht, dann sieht alles sauber aus. 

Gegebenfalls würde ich nur mit eine neue CSS Klasse arbeiten, da die anderen Änderungen große Auswirkung auf  Responsive Design hat.
![screenshot from 2016-05-12 09 34 58](https://cloud.githubusercontent.com/assets/1921992/15207212/dcee207c-1824-11e6-9f0b-8251733ed05b.png)

**Comment by ghost** [comment]
@withanage Welche div id hast du gelöscht? 
Anmerkung zur Sicherheit: Wir manipulieren zwar das Stylesheet nach Herzenslust - aber von dem dynamischen Teil des Quellcodes lassen wir die Finger, d.h. dort löschen wir ohne Anweisung nichts und ergänzen auch nichts.

**Comment by withanage** [comment]
@wwwubhd 
id="downloadTable"
d.h. irgendwie macht die Formatierung durch css von downloadTable

**Comment by nils-stefan-weiher** [comment]
Habe einen kleinen Fehler im book.html view gefunden, der dafür gesorgt hat, dass die Tabelle nicht mehr an der richtigen Stelle sitzt.
Auf dem Testserver sieht es jetzt wieder normal aus:
http://heiup.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog/book/53

**Comment by ghost** [comment]
@isgrim Fantastisch, danke dir! @withanage Wie gesagt: Die Gefahr, dass wir bei dynamischem Quellcode etwas kaputt machen, ist sehr hoch - ich könnte genauso gut versuchen, Rechtschreibfehler in einem russischen Text zu korrigieren ohne Kyrillisch zu beherrschen. Eine funktionierende Möglichkeit, den Code automatisiert auf Validität zu prüfen, kenne ich auch nicht - ein Vergleich der Struktur hat bei mir keine Unterschiede gebracht zu den anderen Plattformen. D.h. wir haben keine sinnvolle Hilfe, um Fehler finden. Und da das CSS das gleiche ist wie bei den anderen Plattformen, und es bei den anderen funktioniert, konnte es die Formatanweisung an sich nicht gewesen sein.

**Comment by withanage** [comment]
@wwwubhd : klar, die visuelle Validät automatisch zu prüfen ist sehr schwierig. Um wenige visuelle Problemen zu bekommen,  versuchen  in Module umzubauen, damit weniger code in html templates vorkommen.  Als Anfang  habe ich das Konzept  für oastatistik Modul eingebaut , damit wir so eingie HTML Module so  umstellen. Natürlich ist es viel Code schreib-arbeit ;-) Aber das  Konzept wird i helfen in Zukunft weniger Fehler zu produzieren. [Code](https://github.com/UB-Heidelberg/UBHD-OMPArthistoricum/blob/master/views/catalog/book.html#L53:L81l)
Wenn  wir irgendwo das OAstatistik block  ausgeben müssen, sollten wir nur das  Code kopieren.
Theoretisch sollten die Anwendungsentwickler euch solche Blocke zur Verfügung erstelle, wo ihr die Style eigenschaften selber festlegen können. Dann passiert so was nicht.
