### ISSUE TITLE
Korrekturen Zitierweise

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#44]
- [x] Hrsg. in Klammern
- [x] Doppelpunkt nach Autoren/Herausgebern
- [x] Verlagsname aus `press_settings` :arrow_forward: `publisher`

**Comment by ankosi** [comment]
Außerdem: 
- [x] Reihe in Klammern hinter dem Jahr angeben: https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/10

Werk, das in einer Reihe erscheint:
Nachname, Vorname: Titel: Untertitel, Ort: Verlag, Jahr (Reihe, Bd. x). doi:xx

**Comment by kadowa** [comment]
@AnjaKonopka, könntest du bitte bei Gelegenheit in http://books.ub.uni-heidelberg.de/UBHD_OMPHeibooks überprüfen, ob die Zitierweise jetzt korrekt ist und, falls ja, das Issue schließen?

**Comment by ankosi** [comment]
Hier http://books.ub.uni-heidelberg.de/UBHD_OMPHeibooks/catalog/book/69 erscheint nach der dritten Herausgeberin noch ein Komma vor (Hrsg.). 

Das Komma bitte entfernen.
