### ISSUE TITLE
Trennstrich nach Autorenbiographie

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#45]
Bitte einen (grauen? @AnjaKonopka) Trennstrich einfügen, um die Autorenbiographie optisch vom Abstract abzusetzen. Im Code (beispielhaft für Arthistoricum, gilt aber für alle) hier:

https://github.com/UB-Heidelberg/UBHD-OMPArthistoricum/blob/master/views/catalog/book.html#L155-L156

**Comment by ankosi** [comment]
Ja, gerne grau.

**Comment by ghost** [comment]
@AnjaKonopka 
Schau mal bitte, ob das so in Ordnung für dich ist:
http://heiup.uni-heidelberg.de/UBHD_OMPHeibooks/catalog/book/70

**Comment by ankosi** [comment]
Der Trennstrich darf gern etwas mehr zu sehen sein. Der Abstand der Autorenbiographie nach oben sollte größer sein, der Trennstrich dabei nahe zur Autorenbiographie.

**Comment by ghost** [comment]
Jetzt besser?

**Comment by ankosi** [comment]
Ja, viel besser. Noch ein Wunsch: Könntest Du die Kurzbio auch von der Kapitelübersicht stärker absetzen? Mit so viel Abstand wie nach oben?

**Comment by ghost** [comment]
So?

**Comment by ankosi** [comment]
Der Abstand nach unten ist perfekt. Könntest Du die Trennlinie noch etwas näher an die Bio ziehen?

**Comment by ghost** [comment]
Jetzt in Ordnung?

**Comment by ankosi** [comment]
Jaaa!!!

**Comment by kadowa** [comment]
:sparkles:  :notes:  :bouquet: :boom: :sparkles:

**Comment by kadowa** [comment]
:innocent:

**Comment by kadowa** [comment]
Testweise in alle Portale umgezogen, z.B.:

http://books.ub.uni-heidelberg.de/UBHD_OMPArthistoricum/catalog/book/80
