### ISSUE TITLE
DOI taucht nicht mehr auf den Katalogseiten in den Portalen auf

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPortal#47]
@withanage @isgrim @kadowa 
Wie Katharina jetzt herausgefunden hat, wird die DOI in OMP so lange nicht als fertig angesehen, solange man den Katalogeintrag nicht aufgerufen hat. Dadurch aber, dass der Katalogeintrag direkt auf die Portaloberfläche weiterlietet, kann man ihn nicht mehr aufrufen. Die DOI bleibt unfertig und wird in diesem Zustand auch nicht auf der Portaloberfläche angezeigt.

**Comment by nils-stefan-weiher** [comment]
Für welche Submissions existieren denn aktuelle noch keine DOIs?

**Comment by kadowa** [comment]
This issue was moved to kadowa/UBHD-OMPPortal#14
