### ISSUE TITLE
ISSN anzeigen (ab OMP-Release 1.2.)

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#49]
@bettinamueller, @nidame  Ab OMP 1.2 kann die ISSN unter "Katalog" (linker Seitenbereich) -> "Reihe" -> Reihen verwalten eingetragen werden. Es gibt sowohl ein Feld für die Print-ISSN als auch für die eISSN. Diese Felder bitte nutzen ab Umstieg auf 1.2 nutzen.

![2016-05-24 13_18_46-greenshot_issn](https://cloud.githubusercontent.com/assets/11088169/15502207/d3f82f66-21b2-11e6-858e-ffae4c052884.png)

@kadowa, @isgrim, @withanage: Bitte diese Information in der rechten Seitenleiste wie hier http://heiup.uni-heidelberg.de/series/hst angeben.

**Comment by kadowa** [comment]
Das wird schwierig, denn die Serieninfoseiten sind (auf ausdrücklichen Wunsch hin) statisch gebaut worden, d.h. die Informationen kommen nicht aus der OMP-Datenbank. Wir können die ISSN nur hier http://heiup.uni-heidelberg.de/series/hst/volumes oder hier http://heiup.uni-heidelberg.de/series automatisch anzeigen lassen.

**Comment by nils-stefan-weiher** [comment]
Ich habe heute nochmal mit Katharina gesprochen und wir können die Info Seiten Modular gestalten. Das heisst nur HTML für die ISSN wir dann dynamisch erzeugt und kann an beliebiger Stelle in den jeweiligen statischen Serieninfoseiten eingebettet werden.
Sobald die Umstellung auf OMP 1.2 passiert ist würden wir das angehen.

**Comment by withanage** [comment]
@isgrim  ja eher das [51](https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/51) als prio.

**Comment by kadowa** [comment]
This issue was moved to kadowa/UBHD-OMPPortal#13
