### ISSUE TITLE
heiUP aktualisieren

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#52]
@kadowa 
Die Überarbeitung, die die anderen Portale erfahren haben, sollte auch für heiUP angegangen werden.

**Comment by kadowa** [comment]
@withanage, bezieht sich #53 hierauf?

**Comment by ankosi** [comment]
Ja. Hardcover als zweites PoD-Format habe ich bisher noch nicht getestet :-(

**Comment by kadowa** [comment]
- [x] Lizenz einfügen
- [x] VG-Wort-Anbindung einbauen
