### ISSUE TITLE
heiup Bücheranzeige braucht folgenden funktionen

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#53]
- Angabe von Reihe und Band (Heidelberg Studies in Transculturality; Band 1)
- Hardcover-ISBN (9783946054047)

wurde von @ankosi gemeldet.

**Comment by withanage** [comment]
@ankosi 
erstmal 
- [x]  hardcover , bitte testen

**Comment by ankosi** [comment]
Auf der heiUP-Seite in jedem Fall richtig. Wo soll ich sonst noch testen?

**Comment by withanage** [comment]
@ankosi  habe in heiup intergriert.  
 In anderen Portale so was nicht vorkommen, da es erweitert wurde. Aber wenn Du in einem anderen Portal  auch testen könnte und falls Probleme gibt, ein Ticket stellen könnte, ist  sehr hilfreich.

**Comment by ankosi** [comment]
Wenn ich in anderen Portalen teste, sind die Änderungen aber gleich auch 
nach außen sichtbar. Oder gibt es eine Möglichkeit, so zu testen, dass 
die Änderungen nur auf dem Testserver zu sehen sind?

**Comment by withanage** [comment]
@ankosi 
die änderungen sind ur in test servern UBHD_xxxx sichtbar. (außer UBHD_OMPPortal)
die test-server sind jetzt nicht mehr  nach außen sichtbar.
habt ihr da in anwender-treffen nicht darüber diskutiert ? wenn nicht kann ich tickets anlegen was zu testen gibt ?

**Comment by ankosi** [comment]
Wird mit #52 erledigt.
