### ISSUE TITLE
Bandanzeige Reihe

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#58]
@kadowa Die Anzeige der Bandbezeichnung einer Reihe soll sich nach der Sprache der Veröffentlichung richten. Bei englischsprachigen Titeln also "vol.", bei deutschsprachigen "Band".

**Comment by ankosi** [comment]
@kadowa. Wie von Dir vorgeschlagen, schreiben wir die Bandangabe in Zukunft direkt neben die Bandnummer. Die Bandbezeichnung aus der Datenbank bitte löschen.

**Comment by kadowa** [comment]
Das hat aber durchaus spürbare Auswirkungen – insbesondere auf die Sortierung der Bände auf den Reihenübersichtsseiten – die allen bewusst sein sollten. Können wir das bitte nochmal im Plenum besprechen?

**Comment by kadowa** [comment]
Nur als Beispiel: Die korrekte Sortierung von Unterbänden mit Nummern wie `2.1` usw. (s. http://books.ub.uni-heidelberg.de/propylaeum/catalog/series/cms) wird dann nicht mehr möglich sein. OMP kann das ohnehin nicht (s. http://serv21.ub.uni-heidelberg.de/omp/index.php/propylaeum/catalog/series/cms), wir hatten das extra eingerichtet.

**Comment by kadowa** [comment]
This issue was moved to kadowa/UBHD-OMPPortal#3

**Comment by kadowa** [comment]
This issue was moved to kadowa/UBHD-OMPPortal#4
