### ISSUE TITLE
doi xasia

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#59]
@wwwubhd 

daniela , wie sollen die dois  hier umgeleitet werden?

http://crossasia-books.ub.uni-heidelberg.de/xasia/catalog/book/60

**Comment by ghost** [comment]
@withanage 
von "https://books.ub.uni-heidelberg.de/index.php/xa/catalog/book/60" auf "http://crossasia-books.ub.uni-heidelberg.de/xasia/catalog/book/60"

**Comment by withanage** [comment]
http und https  werden weitergeleitet.

ist https für doi absichtlich ?

**Comment by ghost** [comment]
Ja, ist es.
