### ISSUE TITLE
Arthistoricum-Bände nicht erreichbar

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPortal#60]
@withanage 
@kadowa 

Wenn derzeit versucht wird, ein Band in Arthistoricum (Portal) aufzurufen, gibt es einen Error. Hier ist der Text aus der Logdatei:
(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> OMPDAL instance has no attribute 'getSubmissionFileSettings'"
p3
sS'layer'
p4
S'/usr/local/web2py/applications/arthistoricum/controllers/catalog.py'
p5
sS'code'
p6

Viele Grüße
Daniela

**Comment by kadowa** [comment]
Funktioniert jetzt wieder, das Submodule war (aus mir unerklärlichen Gründen) weg. Ich habe zuletzt am Donnerstag an Arthistoricum gearbeitet. Habt ihr in der Zwischenzeit irgendetwas gemacht?

**Comment by ghost** [comment]
Danke :-)
Ich wüsste nicht, dass einer von uns etwas daran gemacht hat.
