### ISSUE TITLE
Bände bei Reihenseite in Propylaeum nicht angezeigt

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPortal#62]
@kadowa @withanage @isgrim 
Hallo zusammen,

sobald der Band "Schyłek pradziejów w środkowym Sudanie" (ID:121) in Propylaeum freigeschaltet wird, taucht er zwar ganz normal bei http://books.ub.uni-heidelberg.de/propylaeum/catalog auf, die Seite http://books.ub.uni-heidelberg.de/propylaeum/catalog/series/saa wirft aber einen Fehler.
Im Error-Log steht:
(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> expected string or buffer"
p3
sS'layer'
p4
S'/usr/local/web2py/applications/propylaeum/controllers/catalog.py'
p5
sS'code'
p6

Katrin und ich haben den Band jetzt erst einmal wieder heraus genommen. Wenn ihr das zum Testen aber braucht, gebt Bescheid, dann tragen wir ihn wieder ein.

Viele Grüße
Daniela

**Comment by kadowa** [comment]
Ursache war ein nicht abgefangener Fehler bei leerer Bandnummer (http://books.ub.uni-heidelberg.de/propylaeum/catalog/book/39 hat keine Bandnummer).
