### ISSUE TITLE
Submission does not  appear in portal

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#63]
ich   bin dran.

**Comment by withanage** [comment]
Liebe Bettina,
ich habe es nachgeschaut. 
Könnte sein, das Buch  nicht in einer Serie zugeordnet ist.
http://books.ub.uni-heidelberg.de/arthistoricum/catalog/book/95

**Comment by withanage** [comment]
Liebe Daniela,
@wwwubhd 

> Nach welchen Kriterien trägst du Bände dort ein? Wurde das irgendwann beschlossen? 

 Das Eintragen einer ignore_submissions=nummer  wird nur für heiup gebraucht,  da es  im Test-Portal Buch frei-gegeben wird und vorher überprüft wird.
Die Funktion ist nicht für alle andere Portale nicht wichtig und  kann als 0 gesetzt werden.
 <pfad>/web2py/private/<protal>/appconfig.ini

Viele Grüße,
Dulip

**Comment by ghost** [comment]
@withanage 
Warum war es dann für Arthistoricum eingetragen?

Viele Grüße
Daniela

**Comment by withanage** [comment]
@wwwubhd 
Ich vermute mal es war versehentlich jemand. Normalerweise ändert in der  Datei nichts.
