### ISSUE TITLE
Abstände vor Überschriften

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#66]
Vor Kapitelüberschriften (in Word Formatvorlage Überschrift 2) und Überschriften der Ebene 3 sollen die Abstände größer sein.

**Comment by withanage** [comment]
@ankosi 
bei der Implemntierung ist mir aufgefallen, vielleicht ist es besser allgemein mehr Platz zwischen Überschriften. 
Habe allgemein auf 20 Pixeln gesetzt. Natürlich lässt es einschränken oder auch der Abstand vom unterhalb stehenden Text zusätzlich zu defineren.
