### ISSUE TITLE
omp 1.2  oai  plugin  problem ?

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#68]
@UmbrellaDish hat getestet.
OMP 1.2 sollte lokal installiert werden und getestet werden, ob der Fehler reproduzierbar ist.

**Comment by withanage** [comment]
nils, kannst du bei dir lokal installieren und die schritte   dokumentieren? 
Florian kriegt eine Fehlermeldung,  wir können es zusammen untersuchen.
https://github.com/pkp/omp/tree/omp-stable-1_2_0

**Comment by nils-stefan-weiher** [comment]
Alles klar werde ich machen

**Comment by nils-stefan-weiher** [comment]
Hallo,

habe deswegen nochmal ein Issue bei PKP angelegt:
https://github.com/pkp/pkp-lib/issues/1798

**Comment by withanage** [comment]
@isgrim   Vielen Dank !

**Comment by nils-stefan-weiher** [comment]
Ich würde das auch mal mit OJS 3.0 auf serv21 testen.

**Comment by nils-stefan-weiher** [comment]
OAI scheint unter OJS 3.0 zu funktionieren, aber ich habe es nicht hingekriegt mit "ListRecords" daten anzeigen zu lassen, d.h. ich weiß nicht genau wie der Query aussehen muss, dass auch Daten zurückkommen.

**Comment by nils-stefan-weiher** [comment]
Alec Smecher hat geantwortet und die OAI Schnittstelle mit DCMetadataplugin funktioniert jetzt wieder in omp 1.2.0

**Comment by withanage** [comment]
@isgrim  Danke für dein Einsatz.
Hast Du das patch in serv21 schon getestet ?

**Comment by withanage** [comment]
oh, ja ich sehe es funktionirt.
http://serv21/omp/index.php/heibooks/oai?verb=ListRecords&metadataPrefix=oai_dc&set=heibooks:universitaetsmuseum

**Comment by withanage** [comment]
was denkst du ?  können wir es ins serv3 reinnehmen ?

**Comment by ankosi** [comment]
@isgrim 
Ist das jetzt schon auf serv3?

**Comment by nils-stefan-weiher** [comment]
@ankosi 
Zur Zeit funktioniert es nicht mal mehr auf serv21. Wir benutzten dort die stabile OMP Version 1.2.0.
Ich kam diese Woche nicht dazu zu schauen ob es neue Aktualisierungen gibt.

**Comment by nils-stefan-weiher** [comment]
Der Webserver auf dem OMP Testserver macht Probleme. Ich muss morgen schauen was genau da schief läuft.

Inzwischen gibt es eine [Übersichtsseite im Github Wiki](../wiki/OMP-Plugin-Development) die den Status der verschiedenen Plugins und deren Abhängikeiten aufschlüsseln soll.

**Comment by nils-stefan-weiher** [comment]
Ich habe vermutlich rausgefunden was den Fehler in der OAI Ausgabe von heiup auf dem Testserver verursacht hat. Wenn eine Bestimmte Submission (122), als veröffentlicht in den Katalog übernommen wird geht es, sobald man sie wieder rausnimmt geht es nicht mehr.
Es wird ein Eintrag in einer Datenbanktabelle zurückgelassen, der die OAI Schnittstelle durcheinander bringt.

**Comment by nils-stefan-weiher** [comment]
Auf dem Produktivserver ist es aber ein anderes Problem. Dort gibt es einen Bug in der installierten Version von OMP, der im aktuellen 1.2.0 stable branch von OMP nicht mehr drin ist.

**Comment by withanage** [comment]
> Ich habe vermutlich rausgefunden was den Fehler in der OAI Ausgabe von heiup auf dem Testserver verursacht hat. Wenn eine Bestimmte Submission (122), als veröffentlicht in den Katalog übernommen wird geht es, sobald man sie wieder rausnimmt geht es nicht mehr.
> Es wird ein Eintrag in einer Datenbanktabelle zurückgelassen, der die OAI Schnittstelle durcheinander bringt.

ja,   wenn es reproduzieren lässt, kann man das  als Bug definieren

**Comment by withanage** [comment]
> Auf dem Produktivserver ist es aber ein anderes Problem. Dort gibt es einen Bug in der installierten Version von OMP, der im aktuellen 1.2.0 stable branch von OMP nicht mehr drin ist.

ja,  falls Du auch da den genaueren Grund isolieren kann, dass ist sehr hilfreich.

**Comment by nils-stefan-weiher** [comment]
Hab ein Issue wegen OAI Bug für pkp aufgemacht: https://github.com/pkp/pkp-lib/issues/2033

**Comment by withanage** [comment]
Danke Dir. Können wir den  Produktiven Server auf den gleichen Stand wie der Test-Server  bringen ?

**Comment by nils-stefan-weiher** [comment]
Ich prüfe nochmal wie groß die Änderungen zwischen den Versionen sind

**Comment by withanage** [comment]
super!

**Comment by nils-stefan-weiher** [comment]
Auf anhieb sehe ich nichts außer Bugfixes:
https://github.com/pkp/omp/compare/omp-1_2_0-0...omp-stable-1_2_0

Ich würde allerdings abwarten ob sie vielleicht noch den OAI bug fixen bevor wir produktiv updaten.

**Comment by withanage** [comment]
Das könnte schon etwas dauern, aber wenn keine große Aufwand ist, würde ich das update machen.
Wir  können  @ankosi  fragen, ob sie einen kurzen ein Blick auf den Test-Server  werfen kann, ob kritische  Probleme da sind.

**Comment by ankosi** [comment]
@withanage Was für kritische Probleme könnten das sein? Änderungen, die schon auf dem Testserver umgesetzt wurden, aber noch nicht auf dem Produktivserver?

**Comment by withanage** [comment]
@ankosi 
z.B ,  etwas wird  gespeichert  und nur ein "Loading button" wird gezeigt. In OMP 1.1 gab ja solche Probleme.
Am besten würde da ein Test-Eintrag machen und schauen, ob  alle Schritte ohne Probleme eintragen lässt.

**Comment by ankosi** [comment]
Also einfach mal testen, ob alles auf unsere OMP-Testinstanz läuft? Ist das Instanz, auf der wir schon die ganze Zeit testen konnten, oder gibt es eine neue?

**Comment by withanage** [comment]
> Also einfach mal testen, ob alles auf unsere OMP-Testinstanz läuft? 

ja genau.

**Comment by ankosi** [comment]
Habe jetzt ein Buch auf der Testinstanz hochgeladen. Ich habe nur die Bugs gefunden, die schon vorher da waren. Hat also alles geklappt wie auf der Produktivinstanz.
http://serv21.ub.uni-heidelberg.de/omp/index.php/heiup/catalog/book/177

**Comment by nils-stefan-weiher** [comment]
@ankosi 
Danke, dann schaue ich mal wie wir am besten das Update machen und gebe Bescheid sobald es soweit ist

**Comment by nils-stefan-weiher** [comment]
Update von OMP auf Produktivserver am 7.12.16 gemacht. Ist jetzt auf dem selben Stand wie der Testserver.
Ich habe jetzt auch das XMetaDissPlus plugin angepasst und Fehler beseitigt.
Die Änderungen sind in einem Branch zu finden: https://github.com/UB-Heidelberg/xmdp22/compare/master...omp-stable-1_2_0
Das XMDP-Plugin läuft jetzt auch auf dem Testserver:
http://serv21/omp/index.php/heiup/oai?verb=ListRecords&metadataPrefix=XMetaDissPlus&set=opentest:pubf_pdf
Als nächtes müssten wir überlegen wie man die Ausgabe von XMetaDissPlus Daten gut testen kann.

**Comment by withanage** [comment]
Super.  Hast Du schon auch in wiki die Sachen aktualisiert?
Lass uns mal morgen dazu zusammensetzen.

**Comment by ankosi** [comment]
@isgrim Wie ist denn hier der neueste Stand? Die OAI-Schnittstelle ist für uns bei allen Portalen sehr wichtig.

**Comment by nils-stefan-weiher** [comment]
@ankosi Die OAI Schnittstelle läuft seit dem 7.12. jetzt auch Produktiv. Entschuldige falls das nicht klar war.
