### ISSUE TITLE
Statistikhinweis nur bei den relevanten Büchern anzeigen

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPortal#69]
- [x]  heibooks
- [x]  propylaeum
- [x] xasia
- [x] arthistoricum

Wie besprochen:
Bei den Büchern, die vor dem 7.3. erschienen sind, soll der Hinweis erscheinen, dass der Statistikzeitraum erst ab diesem Datum greift. Bei allen anderen Büchern soll dieser Hinweis nicht stehen, da nicht relevant.

Am schönsten wäre es, wenn man das irgendwie aus OMP heraus filtern könnte. Zur Not muss das ganze aber über hardcodiert eingetragene IDs erfolgen.

Viele Grüße
Daniela

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela,
kannst Du mir erstmal paar betroffene Submisstion IDs eintragen, damit ich die Datenbank untersuchen kann.

**Comment by ghost** [comment]
Vor allem bei Propylaeum dürfte es einige geben. Z.B. 17 - 19 dürften dazu gehören.

**Comment by withanage** [comment]
@wwwubhd 
 Wird diese Abfrage etwa alle Bücher etnsprechen, die ihr in statistik aufnehmen wollt ?

> SELECT \* FROM omp.submissions where date_submitted < "2015-07-13 0:0:0";

**Comment by ghost** [comment]
Ich denke, das sieht gut aus. Das Datum stimmt aber noch nicht:

> SELECT \* FROM omp.submissions where date_submitted < "2016-03-07 0:0:0";
> (Zumindest ist es das Datum, was wir vorher als Hinweis eingeblendet haben.)

Sicher sagen können aber nur Bettina, Katrin und Anja, ob das alle sind.

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela.
kannst Du mir das deutsche Text zuschicken, was ausgegeben werden muss, falls die Bücher vor dem obigen Datum eingetragen wurde.

**Comment by ghost** [comment]
Hallo Dulip,

das hier haben wir uns überlegt:
"Aufgrund technischer Gegebenheiten beginnt die statistische Erfassung für diesen Titel erst am 07.03.2016"

Viele Grüße
Daniela

**Comment by withanage** [comment]
Liebe Daniela, 
auf english  so was  ?
The statistical recordings  begin from  03.07.2016  due to  technical reasons

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela,
wie wäre  die Mledung  als ein popover  oder wie hättet iht das anders ausgegeben?
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/catalog/book/123

**Comment by withanage** [comment]
@wwwubhd 
Liebe Danieal,
zum Testen
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/catalog/book/43

**Comment by ghost** [comment]
Ich habe es weitergegeben und warte, was die anderen sagen :)

**Comment by ankosi** [comment]
Auf Englisch bitte diesen Text eintragen:

For technical reasons, statistical data is available from 03.07.2016 onward.

**Comment by withanage** [comment]
onward(s) oder ?

**Comment by ankosi** [comment]
Onwards wäre natürlich auch korrekt. Aber ich finde, es reicht hier, eine Variante des Wortes zu zeigen und würde bei onward bleiben.

**Comment by withanage** [comment]
@wwwubhd  @ankosi 
in heiup ist ein Buch zum testen da.
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/catalog/book/43?lang=en
Datum war 3.Juli oder 7.März 2016 ;-)  um ganz  sicher zu sein?

**Comment by ankosi** [comment]
Richtig müsste 7. März 2016 sein. Das betrifft meines Wissens aber nicht 
die heiUP-Seiten, oder Florian? Die Habenstein-Statistik sollte doch 
stimmen?

**Comment by ankosi** [comment]
Die Statistikanzeige bitte auch bei der Kapitelstatistik einbauen.

**Comment by withanage** [comment]
> Richtig müsste 7. März 2016 sein. Das betrifft meines Wissens aber nicht die heiUP-Seiten, oder Florian? Die Habenstein-Statistik sollte doch stimmen?

stimmt, habe einfach wegen Datum in heiup eingebaut.  werde rausnehmen und in andere Portale einbauen,

**Comment by ankosi** [comment]
Zur Kontrolle: Der Hinweis sollte bei heiBOOKS bei folgenden OMP-IDs Sollte auftauchen: 11, 69, 70. Alle anderen heiBOOKS-Titel sind später erschienen.

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela,
habe jetzt alle Portale mit Hinweis bestückt.
Falls visuelle Änderungen gemacht werden muss, lass mich wissen.
Ist als Modul  jetzt in alle Portale außer in heiup gebunden.

**Comment by withanage** [comment]
@ankosi @bettinamueller 
Liebe Anja und Bettina,
jetzt sind alle Portale zum Testen frei.
Ist kthth die Kathrin ?

@ankosi 
heibooks: 11, 69, 70.  habe ich schon getestet.

**Comment by ghost** [comment]
@withanage 
Schaust du bitte einmal bei heiUP? Da taucht der (englische) Hinweis bei allen Bänden auf.

**Comment by withanage** [comment]
mündlich besprochen und weg-genommen.

**Comment by ghost** [comment]
@withanage 
Das hier ist der Band, den ich meinte: http://books.ub.uni-heidelberg.de/arthistoricum/catalog/book/79?lang=de

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela,
das ist schon was ich auch gefunden hatte. Ist in der Refacturing berücksichtigt.
http://books.ub.uni-heidelberg.de/UBHD_OMPArthistoricum/catalog/book/79?lang=de

**Comment by ghost** [comment]
@withanage 
Danke!

**Comment by withanage** [comment]
@ankosi  @bettinamueller  @katbe  @wwwubhd  
in alle Test -portale  ist  jetzt  der Statistik -Hinweis eingeschaltet  (außer in heiup)  
Je nach Zustimmung werde ich einzelne Produktions-portale updaten.

**Comment by ankosi** [comment]
@withanage 
Danke! heiBOOKS ist ok., kann in die Produktivinstanz übernommen werden.

**Comment by withanage** [comment]
@ankosi 
habe heibooks aktualisiert. 

@bettinamueller @katbe 
habe jetzt auch propylaeum  aktualisiert, da Danieala einige Änderugen brauchte.

Also noch fehlt die Zustimmung für  cross-asia und arthistoricum

**Comment by bettinamueller** [comment]
Gerne auch für arthistoricum.

**Comment by withanage** [comment]
@bettinamueller 
arthistoricum ist auch online jetzt.

**Comment by withanage** [comment]
crossasia auch aktualisiert.
