### ISSUE TITLE
Autoren werden beim Inhaltsverzeichnis nicht neben den einzelnen Beiträgen angezeigt

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPPortal#7]
_From @danielawolf on February 29, 2016 14:26_

@kadowa @withanage 

Beim Aufruf eines Buchs wird zwar das Inhaltsverzeichnis mit allen PDFs angezeigt, nicht aber, welcher Autor welchen Teil geschrieben hat.

Viele Grüße
Daniela

_Copied from original issue: UB-Heidelberg/UBHD-OMPArthistoricum#2_

**Comment by kadowa** [comment]
@withanage, zur Erklärung: Es geht darum, bei Sammelbänden (bei Monographien wohl eher nicht, oder @wwwubhd?) in der Buchansicht zusätzlich zum _chapter title_ auch den _chapter author_ anzuzeigen. Z.B. hier: http://heiup.uni-heidelberg.de/UBHD_OMPArthistoricum/catalog/book/49

Wie das ganze letzlich aussehen soll, müsste aber noch genauer spezifiziert werden.

**Comment by withanage** [comment]
@wwwubhd  
Anhängen ist kein thema,  wie sollte das aussehen? Eine neue Spalte oder mit , Hinter dem Titel 
 Man sollte berücksichtigen, dass es auch in kleinere  Geräte angezeigt ist wie hier.
![screenshot from 2016-03-18 16 45 11](https://cloud.githubusercontent.com/assets/1921992/13883186/99fd64f2-ed28-11e5-930f-394cc52e3da0.png)

**Comment by ghost** [comment]
@withanage @AnjaKonopka 
Anja, was denkst du denn? Ich fände eine neue Spalte nicht schlecht oder aber vielleicht den Namen unter den Titel (kann man ja dann kleiner und kursiv setzen)

**Comment by ankosi** [comment]
@wwwubhd, @withanage, ja, finde ich eine gute Idee. Die Autoren gerne etwas kleiner und farblich etwas schwächer als der Titel. Ich würde ausprobieren, ob es nicht besser ist, die Kapitelüberschriften nicht mehr wie den den Rest des Seitentextes grau, sondern schwarz zu setzen (wie "Inhaltsverzeichnis), sonst sieht man die Autoren gar nicht mehr.

**Comment by ghost** [comment]
@AnjaKonopka @withanage 
Das zu gestalten ist nicht das Problem. Allerdings müssen Kapitelüberschrift und Autorenname gesondert ansprechbar sein, was sie momentan nicht sind. Dulip, könntest du bitte beides in ein Div setzen und mit einer Klasse versehen?
