### ISSUE TITLE
Codierung von Textboxen in Word, Jats XML und Lensviewer

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPPortal#72]
In einer Publikation haben wir Textboxen mit Legende. Wie sollen wir diese in Word codieren, damit myTypeset sie richtig kodiert und der Lensviewer sie richtig darstellt?

Jats kennt ein entsprechendes Element, in Jats könnte man die Textboxen wie folgt kodieren:
`
<boxed-text id="xyz123">
   <label>Kasten 1</label>
   <caption>Climate Engineering als neuer technischer Exzess im Anthropozän</caption>
   <sec>...</sec>
</boxed-text>
`
Beispiel:

![box1](https://cloud.githubusercontent.com/assets/15726653/18306074/7b09f2b4-74ea-11e6-840e-cab8ebc80312.png)
![box2](https://cloud.githubusercontent.com/assets/15726653/18306073/7b064ed4-74ea-11e6-82e0-6a74a4d5805e.png)

**Comment by withanage** [comment]
habe nach mpt exportiert.

**Comment by ghost** [comment]
@withanage Drei Möglichkeiten, Textboxen in Word zu erzeugen:

1: Rahmenlinien um den Text: [Boxed Text Example 1.docx](https://github.com/UB-Heidelberg/UBHD-OMPPortal/files/459036/Boxed.Text.Example.1.docx)
2: Box in Tabelle mit einer Zelle: [Boxed Text Example 2.docx](https://github.com/UB-Heidelberg/UBHD-OMPPortal/files/459037/Boxed.Text.Example.2.docx)
3: Textrahmen, der vom restlichen Text umflossen wird: [Boxed Text Example 3.docx](https://github.com/UB-Heidelberg/UBHD-OMPPortal/files/459035/Boxed.Text.Example.3.docx)
