### ISSUE TITLE
bestimmte serien und ihre  Submissions ausblenden

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#73]
- [ ]  Bestimmte Reihen   darf nicht unter reihen vorkommen
- [ ] eine Reihe für alle einzlen Bücher

**Comment by ankosi** [comment]
Wird in Zukunft nicht nötig sein. Siehe neues Konzept mit Spartenbildung 

https://github.com/kadowa/UBHD-OMPPortal/issues/33
