### ISSUE TITLE
[Enhancement] OAStats

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#74]
- [x]  Python modules makes two calls to server, which takes more than 1.5 seconds.
  Portale
- [x]  heiup
- [x]  heibooks
- [x]  propylaeum
- [x] xasia
- [x] arthistoricum

**Comment by withanage** [comment]
@wwwubhd   ich schreibe das oastatistik modul neu, daher bitte das heiup produktiv instanz nicht updaten, bis ich frei-gebe.

**Comment by withanage** [comment]
@isgrim  FYI

@wwwubhd 

Liebe Anna , Daniela und Nils,
ich habe jetzt die Statistik Modul umgeschrieben, damit  die Büchserseiten schneller geladen werden.
Könnte jemand das mit internet explorer testen, da es jetzt  client-seitig gemacht wurde.
http://heiup.uni-heidelberg.de/catalog/book/43
http://heiup.uni-heidelberg.de/catalog/book/90

Nachdem Tests würde ich es in alle andere Portale integrieren.

Alle Commits von Heute müssen jetzt in github sein.

**Comment by ghost** [comment]
@withanage 
da scheint etwas noch nicht zu stimmen:
![test](https://cloud.githubusercontent.com/assets/14978254/18381423/764450c4-767c-11e6-80b3-e41691685377.png)
Das gilt aber nicht nur für den IE, der Mozilla zeigt das auch an.

**Comment by withanage** [comment]
@wwwubhd  Danke für den Hinweis.
Könntest Du jetzt mit Strg+F5 versuchen ? 
Falls nicht geht , kannst Du mir bitte  das HTML-Snippet zuschicken.

**Comment by ghost** [comment]
Jetzt sieht es bei beiden Browsern wieder gut aus :-)

**Comment by withanage** [comment]
Danke nochmals fürs Testen !
Endlich liegen wir   unter 1.5 Sekunden für die Bücherseite  in heiup

**Comment by withanage** [comment]
@wwwubhd 
jetzt möchte ich diese Verbeseerung auf alle portale übernehmen.
Habt ihr zufälligeweise bei anderen Portalen views/catalog/book.html  geändert ?
falls nicht kann ich sie einfacher überschreiben.
ich kann es auch selber aussuchen, aber wenn ihr "nein" sagt  kann ich die such sparen.

**Comment by ghost** [comment]
@withanage Ja, wenn ich mich richtig erinnere, hat Daniela zumindest auf xasiaBooks die Vorschau aktualisiert... (Evtl. auch auf ArtBooks, aber ich kann es dir leider nicht sicher sagen.)

**Comment by withanage** [comment]
@wwwubhd  
Liebe Anna,  
Danke, dann frage ich ihr dann nächste  Woche an  und  übernehme eins-nach-einander!
Dann kann ich gleich das Ticket auch ran gehen. https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/69

**Comment by ghost** [comment]
@withanage 
Die Datei habe ich bei Xasia am 7. September umgeschrieben.

Bei den anderen Portalen sind alle Änderungen schon ein ganzes Stück länger her.

Viele Grüße
Daniela

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela,
Danke ! d.h. ich  muss eher einzelne Dateien  editieren außer einfach erstetzen.
Welche Portale sind wenige betroffen von eure Änderungen zur Zeit ?

**Comment by ghost** [comment]
@withanage 
Ich glaube heiBooks geht halbwegs. Die letzten Änderungen sind da 12 Tage her.

**Comment by withanage** [comment]
ok. ich fange damit an

**Comment by withanage** [comment]
@isgrim  @wwwubhd 
Liebes  Web-team und Nils,
habe ein test-gemacht und branch auf master umgestellt. Daher ist nicht fertig, melde bei euch wenn Test-instanz Heibooks wieder stabil ist.

**Comment by withanage** [comment]
@wwwubhd @isgrim 

Liebe Daniela,
heibooks stats ist zum Testen frei.
http://books.ub.uni-heidelberg.de/UBHD_OMPHeibooks/catalog/book/69

Lieber Nils,
habe wie versprochen, integriert.
Für dein Referenz

https://github.com/UB-Heidelberg/UBHD-OMPHeibooks/commit/0ba5e42e575aa1112963e39766269bc9a3b2ab58
https://github.com/UB-Heidelberg/UBHD-OMPHeibooks/commit/027dbdb1ec0d3694fc17462e1fc9271175ef3628

**Comment by ghost** [comment]
@withanage @isgrim 

Beim Mozilla, Chrome und IE habe ich keine Auffälligkeiten feststellen können :-) (Außer, dass der Platz für die Überschriften nicht ausreicht, aber das hat nichts mit deinen Änderungen zu tun)

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniea ,
Danke !  habe das Produktive Instanz upgedatet. 
Für Rest der Portale habt ihr ein bestimmte Präferenz-Reihenfolge ?

**Comment by ghost** [comment]
@withanage @isgrim 

Arthistoricum sollte heute und morgen davon ausgenommen sein, aber der Rest ist frei.

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela,
Propylaeum ist zum Testen frei.
http://books.ub.uni-heidelberg.de/UBHD_OMPPropylaeum/catalog/book/145

**Comment by ghost** [comment]
@withanage 
Lieber Dulip,

auch hier sieht für mich alles in Ordnung aus.

Viele Grüße
Daniela

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela, Danke. 
auch produktive instanz upgedatet.

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela.
crossasia ist frei zum Testen.
http://books.ub.uni-heidelberg.de/UBHD_OMPXAsia/catalog/book/126
http://books.ub.uni-heidelberg.de/UBHD_OMPXAsia/catalog/book/124

**Comment by ghost** [comment]
@withanage 
Auch das sieht gut aus :-)

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela, habe auch das Produktive Instanz upgedated.
Gib mir Bescheid, wenn ihr arthistoricum frei-gbit.

**Comment by ghost** [comment]
@withanage 
Lieber Dulip,

ich denke, du kannst Arthistoricum jetzt übernehmen.
Gibt es eine Instanz, die ich die nächsten Tage in Beschlag nehmen könnte (außer Xasia und heiUP)?

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela,
du kannst alle außer artihitoricum und  heibooks  ganz normal nutzen. Ich habe alles schon gemergt.
In heibooks sind @isgrim  s Änderungen fürs Testen eingeblendet.  https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/51

**Comment by ghost** [comment]
@isgrim @withanage 
Gut, dann nehme ich mir Propylaeum vor

**Comment by withanage** [comment]
@wwwubhd 
Liebe Daniela,
arthistoricum ist auch zum testen frei.
http://books.ub.uni-heidelberg.de/UBHD_OMPArthistoricum/catalog

**Comment by ghost** [comment]
@withanage 
Die Statistik sieht gut aus. Bei der Gelegenheit ist mir aber aufgefallen, dass die EVA-Bände (die gelben) einen Fehler werfen. Das ist in der Produktivinstanz nicht der Fall.

**Comment by withanage** [comment]
@wwwubhd 
danke.  ich schaue das  an , mir ist auch noch aufgefallen, dass Monograhien onhe eine haupt-pdf Datei ein Fehler verwefen.

**Comment by withanage** [comment]
@wwwubhd  ist gefixt.

**Comment by ghost** [comment]
@withanage 
Danke :-)

**Comment by withanage** [comment]
@wwwubhd 
Liebe Danieala,
habe auch propylauem upgedated. damit wird  das Ticket geschlossen :-)

**Comment by withanage** [comment]
Summe  kommt verdoppelt vor
