### ISSUE TITLE
ISBN-Anzeige in der linken Spalte

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#75]
@wwwubhd  
Seit einiger Zeit erscheint wird auf der heiUP-Seite, z. B. hier:

http://heiup.uni-heidelberg.de/catalog/book/123?lang=de 

ISBN

978-3-94777-22-1 (PDF)

978-3-94777-22-2 (Hardcover)

Veröffentlicht am .

rot angezeigt, als ob es Links wären. Diese Informationen sollen wieder in grauer Schrift sein.

Außerdem bitte "ISBN" etwas stärker von der CC-BY-Lizenz absetzen.

**Comment by ankosi** [comment]
Vielleicht hängt die falsche Anzeige der ISBN damit zusammen, dass ich den CC-BY-Lizenz-Text nicht richtig einfügen kann? Das CC-BY-Icon taucht ebenfalls nicht auf.

**Comment by withanage** [comment]
@ankosi 
Das CC-By-Lizens-text habe ich wieder richtig eingefügt. Vielleicht lag es wirklich  daran.
Falls das Problem noch besteht, kannst Du bitte ein screenshot hochladen?

**Comment by ankosi** [comment]
Jetzt ist es richtig, danke! Könntest Du bitte hier http://heiup.uni-heidelberg.de/catalog/book/102?lang=en auch noch mal schauen? Da fehlt ebenfalls das Icon und die Lizenz erscheint gleich zweimal untereinander.

**Comment by withanage** [comment]
@ankosi  habe auch mit dem text ersetzt. am besten, ich trage es  selber für neue bücher ;-) omp  ticket ist noch nicht erledigt.
