### ISSUE TITLE
 Arthistoricum im Feld "supporting Agencies" den jeweiligen Partner / Herausgeber eingetragen

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#77]
Technische  Info
![screenshot from 2017-01-23 14 45 52](https://cloud.githubusercontent.com/assets/1921992/22206225/b1126704-e17a-11e6-80d4-40010e37a1cb.png)
SELECT * FROM omp1_2.controlled_vocab_entry_settings where setting_name="submissionAgency";

Abstimmungen
- eine Liste von Controlled Vocabulary Entries gepflegt

_________________________________________________________________
Gültig für alle Portale
- [ ]  heibooks
- [ ]  propylaeum
- [ ] xasia
- [ ] arthistoricum

**Comment by withanage** [comment]
@wwwubhd @bettinamueller 
Liebe Daniela und Bettina,
Falls ich es richtig verstehe
ihr möchtet 
 **ad picturam Fachverlag für kunstwissenschaftliche Literatur e. K**. 
aus OMP holen ?

![screenshot from 2016-09-15 11 36 52](https://cloud.githubusercontent.com/assets/1921992/18545287/c472bf7c-7b38-11e6-8530-ef4142db5519.png)

**Comment by ghost** [comment]
@withanage @bettinamueller 
Nein, wir haben bei den Titeln, die von ad picturam sind, in das Feld "supporting Agencies" den Namen "ad picturam" eingetragen (in der Datenbank ist es unter "submissionAgency" in der u.a. in der Tabelle "controlled_vocab_entry_settings" zu finden). Wir wollen uns nun den jeweils neuesten Band, der diesen Namen in "supporting Agencies" hat, ausgeben lassen.

Viele Grüße
Daniela

**Comment by withanage** [comment]
Stand: wird am 26.09. mit Maria gesprochen  und  je nach Priorität in Angriff genommen

**Comment by ankosi** [comment]
Siehe zu diesem Issue auch den Issue mit dem gleichen oder ähnlichen Thema: https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/79. 

Doku dazu auch unter 26 Issue in https://github.com/kadowa/UBHD-OMPPortal/issues/26. Dort geschlossen.

**Comment by withanage** [comment]
@ankosi , @wwwubhd 
wird hier das (Submission Agency) Controlled Vocabulary Entry in mehere Sprachen gepflegt oder nur das original Wert ?
z.B. Zur Zeit : "Staatliche Museen zu Berlin" auch in english  genauso eingetragen. Was ist  am besten für Euch ?

**Comment by ankosi** [comment]
@withanage @bettinamueller @nidame @wwwubhd 
Nur den Originalwert. Am besten sollte der Name genauso eingetragen werden, wie in der GND verzeichnet ist. Dann haben wir später keine Probleme, wenn wir auf Normdaten umsteigen möchten.
