### ISSUE TITLE
Filterung

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#78]
TODO 

Sparten

 - [x]  einzelne Kategorisierte
-  [x]  Spartenname auf DE und EN
-  [x]  Kategorie-ausgabe
- [x] "Newest to oldest" und "Oldest to newest"
- [x]  Filterung nur wenn es minimum 20  ist.

**Comment by withanage** [comment]
ist  zu viel in der Reihenfolge, kann man das Halb-jahres Rhythmus  in Milestones eintragen ?

**Comment by ankosi** [comment]
@withanage 
Kann den Rhythmus für alle Milestone der Prio 3 von April auf Juli verschieben. Reicht das?

**Comment by withanage** [comment]
ja, genau.  das  2-mal im Jahr Rhythmus. Dann kann ich  in IT- das auch synchron halten.

**Comment by ankosi** [comment]
ok.

**Comment by withanage** [comment]
![screenshot from 2017-01-11 16 01 42](https://cloud.githubusercontent.com/assets/1921992/21853432/642b37f2-d817-11e6-889d-361ecbfa6a63.png)

**Comment by ghost** [comment]
![layout_heiup_spartenkennzeichnung](https://cloud.githubusercontent.com/assets/14978254/22247857/378fb464-e23c-11e6-982d-901225370b29.jpg)
Layout für a) das Abfragefeld [Sortieren nach...] und b) die Spartenmarker

**Comment by withanage** [comment]
```xml
 <select name="form" onchange="location = this.options[this.selectedIndex].value;">
 <option value="x.html"></option>
</select>
```

**Comment by ankosi** [comment]
In OMP git es bei Kategorien auch die Möglichkeit, die Sortierreihenfolge (nach Titel, Erscheinungsjahr etc.) auf der Kategorienseite festzulegen.
![2017-01-25 09_21_55-greenshot](https://cloud.githubusercontent.com/assets/11088169/22286165/8947b074-e2ee-11e6-9746-23c9ec8c291a.png)

**Comment by withanage** [comment]
@ankosi  habe das auch gesehen, . Diese Funktion ist eher für eine richtige Kategorie seite oder ?

**Comment by ankosi** [comment]
@withanage, @wwwubhd  Ja. Ich dachte, dass es auch für Sparten eigene Seiten geben soll. In der Hauptnavigation "Sparten", dann Unterseiten zu den verschiedenen Sparten (ähnlich wie bei den Seiten "Über uns"). Habe ich da etwas missverstanden?

**Comment by withanage** [comment]
@ankosi 
Die Idee klingt eher logisch. Habe aber anders verstanden, das es nur bei der Liste nach sparten sortiert werden muss und  Spartenname ausgegeben werden muss.
man kann es beliebig komplexer  vortellen.

Vielleicht  lass uns  mit A..a  zusammen-setzen ?

Habe unten noch die erst Gedanken.

----
 Sortier  nach Sparten wird alphabetisch sortiert 

Campus Media 1 (alle nach Datum wie jetzt)
Campus Media 2 (alle nach Datum wie jetzt)

oder braucht man zwei Funktionen 

Sortier nach Spartenname A-Z 
Campus Media 1 (alle nach Datum wie jetzt)
Campus Media 2 (alle nach Datum wie jetzt)

Spartenname Z-A
Campus Media 2 (alle nach Datum wie jetzt)
Campus Media 1 (alle nach Datum wie jetzt)

Oder noch etwas komplexer : 
 Sortier  nach Sparten: 
dann kommt
Z.B. 
Campus Media (Sortiert nach der Kategorie  Einstellungen)
E-Campus Media (Sortiert nach der Kategorie Einstellungen)

**Comment by ghost** [comment]
@withanage 
Der Link bei der SOrtierung soll mit "sort-by" ausgegeben werden, in der Art wie
https://heiup.uni-heidelberg.de/catalog/index?sort_by=sparte=20

**Comment by ghost** [comment]
@withanage @ankosi 
Und: Ja, Zusammensetzen scheint mir sehr sinnvoll - offenbar scheinen sich die Vorstellungen von der Ausgabeseite gerade weiterzuentwickeln...

**Comment by withanage** [comment]
Paar  Informationen,  die  bei URL Überlegungen  interessant sind

 -  Struktur Einträge müssen ziemlich nah an dem  Titel stehen
-  Stop-words machen keine Probleme für URLs
 - je kürzer deso besser. Daher ist eine gute Strukturierung  besser.
-  Keine Hahstags in URLS
-  Gleiches Wort in URL nicht wiederholen
- Bindestriche werden vorgezogen
- Technische  Einschränkungen : https://d1avok0lzls2w.cloudfront.net/uploads/blog/54ea8746e0e803.90711764.jpg

**Comment by withanage** [comment]
Vorschlag für URL Struktur
![url_structure_catalog](https://cloud.githubusercontent.com/assets/1921992/22427074/013e43d8-e702-11e6-9e98-3f3974a4c02c.png)
 Vorüberlegungn

**Comment by withanage** [comment]
Mehr ...
https://seomoz.app.box.com/shared/g4ju1fc4it
http://mysiteauditor.com/blog/wp-content/uploads/2014/10/how-to-optimize-url-for-seo.jpg

**Comment by withanage** [comment]
@ankosi  @wwwubhd 

Jede  Sparte sollte  je nach  OMP-Backend Einstellung sortiert ausgegeben werden oder ?
![screenshot from 2017-02-06 12 49 08](https://cloud.githubusercontent.com/assets/1921992/22646088/d4b3c2a2-ec6a-11e6-9dfd-b2fbf50cde6c.png)

**Comment by ankosi** [comment]
Zunächst soll es Sparten ja nur in einem Backend geben. Die Sortiereinstellungen sollten ansonsten aber je Backend ausgegeben werden, da bei Plattformen mit vielen Retrodigitalisierungen anderen Sortierfunktionen sinnvoll sein könnten als bei Plattformen ohne Retrodigitalisierung.

**Comment by withanage** [comment]
@wwwubhd  @ankosi 

Anbei der ersten Vorschlag für die Navigation. ( Kurzfristig eingeschaltet ) 
In heiup sehen wir nicht zu viele  Bücherwie in andere Portale. Daher  habe ich "items per page" als 2,3,4 zum Testen eingeschaltet.

Es ist nur die Funktionalität da.
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/catalog/index

Für Visuelle Änderungen würde ich am Ende der Implementierung  Web-Team fragen.

**Comment by ghost** [comment]
@withanage @ankosi 
Ich finde, das ist schon sehr gut. Visuell müssen wir natürlich das Ganze noch an das Layout angleichen.
Was mir bei der Gelegenheit aber aufgefallen ist: Die Neuankündigungen finde ich nun etwas verwirrend an der Stelle. Dadurch, dass die logischerweise nicht von der Anzeigenumstellung betroffen sind, habe ich zuerst gedacht, es funktioniert nicht. Ich denke, wir müssen die entweder optisch stärker absetzen oder uns eine andere Stelle überlegen, wo man die unterbringen könnte.

**Comment by withanage** [comment]
@wwwubhd 
ja, für Neuankündigungen eine seperate Stelle  z.B. (catalog/fortcoming) wäre von technischenr Sicht am besten.
Vorteile:
- Die Neuerscheinungen werden nicht jedesmal geladen.
- Eine seperate sauebere Link könnte an externe Beteiligten gegeben werden.

**Comment by withanage** [comment]
@ankosi @wwwubhd 

- [x]  die  Reihenfolge von peer-view nach oben
- [x]  Suche vorübergehend ausgeschaltet

**Comment by withanage** [comment]
@ankosi  @wwwubhd  
wie am Freitag besprochen, anbei noch das Sparten-feld in gleiche Layout-element
http://heiup.uni-heidelberg.de/UBHD_OMPPortal/catalog/index
![screenshot from 2017-05-15 11 28 32](https://cloud.githubusercontent.com/assets/1921992/26051165/a9056568-3961-11e7-9eff-0a1f8b99458c.png)

**Comment by ankosi** [comment]
"Sort by Date" sortiert gerade die ältesten Titel an den Anfang und die neuesten ans Ende. Als Default wäre die umgekehrte Reihenfolge besser. Noch besser wäre, wenn man von "Newest to oldest" und "Oldest to newest" suchen lassen könnte.
Hatten wir nicht auch "Sort by author" vorgesehen? Das fände ich ebenfalls wichtig.

**Comment by withanage** [comment]
> Sort by Date" sortiert gerade die ältesten Titel an den Anfang und die neuesten ans Ende. Als Default wäre die umgekehrte Reihenfolge besser. Noch besser wäre, wenn man von "Newest to oldest" und "Oldest to newest" suchen lassen könnte.

das geht kann ich einbauen.

> Hatten wir nicht auch "Sort by author" vorgesehen? Das fände ich ebenfalls wichtig.
Die Speizifikation  etwas schwierig, wenn mehrere Autoren vorkommen, wie die Reihenfolge bestimmt werden soll.
Wenn nur ein Autor, dann ist es klar,  (Vorname oder nachname)
Wenn mehrere Autoren da sind und bei einigen vielleicht nachname oder nachname fehlt,  kann die Situtation schnell unübersitchtlich werden.

Autoren wäre  eher in einer Suche sinvoll und dachte so hatten wir spezieifert.
