### ISSUE TITLE
HTML Snippets Modularisierung

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#81]
@wwwubhd  
Liebes Web-Team,
 wir möchten allgemeine HTML Funktionen von Poralen rausnehmen.
Dann können wir HTML Seiten etwas klein halten.
theoretisch könnten wir überlegen, dass wir alle  html Blöcke, Javascript Dateien, die  nicht zur Web-Redaktion  gehören in einem git-projekt packen.
Dann werden solche Bllöcke in HTML stehen
`
< -statistik begin --->
{{include 'static(git-project/views/my.html'}}
< --statistik  end --->
`
Jetzt die Frage:
Habt ihr da in andere Projekte  Beiespiel schreib -Konventionen für solche Template Blöcke , wo ihr  gewohnt sind ?

**Comment by withanage** [comment]
zuerst mal als Vorschag  implementiert: 
https://github.com/UB-Heidelberg/omp-resources

**Comment by ghost** [comment]
@withanage 
Lieber Dulip, 
ich würde das gerne nächste Woche besprechen, wenn alle aus dem Urlaub wieder da sind. Ich kann "trocken" schlecht abschätzen, was das genau für Auswirkungen hat. Ich würde mich Mo melden mit einem Terminvorschlag - ok? (Prinzipiell sehen die Template-Notationen, die auf den UB-Seiten verwendet werden, in etwa so aus, wie das, was du geschrieben hast.)

**Comment by ghost** [comment]
@withanage @isgrim Wenn ich Nils vorhin richtig verstanden habe, werden die dynamischen Teile aus der Seite ausgelagert und quasi durch eine Notation "höhere Ordnung" ersetzt, richtig? (Ich hatte das im issue zunächst anders herum verstanden und war deshalb reichlich verwirrt.)
Wenn ihr die Bereiche wie im Bsp. kennzeichnet, damit man im Quellcode gleich sieht, wo einer anfängt und wo einer aufhört, können wir damit gut arbeiten.

**Comment by withanage** [comment]
@wwwubhd 

> werden die dynamischen Teile aus der Seite ausgelagert und quasi durch eine Notation "höhere Ordnung" ersetzt, richtig?

ja.  habe die snippets mit HTML kommentare versehen.
Sie sind immer mir Begin-und-End Kommentare in Code.
[Reviews](https://github.com/UB-Heidelberg/UBHD-OMPPortal/blob/master/views/catalog/book.html#L162:L164)

[OAStats](https://github.com/UB-Heidelberg/UBHD-OMPPortal/blob/master/views/catalog/book.html#L59:L68)

**Comment by ghost** [comment]
@withanage Yep, hab's gesehen - wie gesagt, wenn die Kommentare das kennzeichnen, ist es unproblematisch.
