### ISSUE TITLE
Nachbesserung Empfohlene Zitierweise

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#84]
<a href="https://github.com/ankosi"><img src="https://avatars.githubusercontent.com/u/11088169?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ankosi](https://github.com/ankosi)**
_Thursday Sep 22, 2016 at 10:47 GMT_

---

Bitte ändern: Wenn es mehr als drei Autoren / Herausgeber gibt, bitte nur den ersten nennen und danach "et al." setzen: "Müller, Wolfgang et. al.:"

**Comment by withanage** [comment]
<a href="https://github.com/isgrim"><img src="https://avatars.githubusercontent.com/u/2169369?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [isgrim](https://github.com/isgrim)**
_Thursday Sep 22, 2016 at 12:09 GMT_

---

@ankosi Ich habe die änderungen für alle Portale übernommen und sie sollte jetzt auf den jeweiligen Test instanzen zu sehen sein.

@withanage 
Kannst du die Änderungen dann später Produktiv schalten sobald das ok kommt?

**Comment by ankosi** [comment]
Änderungen sind produktiv.
