### ISSUE TITLE
DOI und URN Plugin

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#86]
@isgrim 
Lieber Nils,
könntest Du bei Gelegenheit , die beide plugin im Test-server testen und  falls Probleme gibt , posten

**Comment by nils-stefan-weiher** [comment]
Meinst du mit omp 1.2.0 stable?

**Comment by withanage** [comment]
ja,  falls nicht geht, würde ich kurz lokal mit   master branch testen

**Comment by nils-stefan-weiher** [comment]
[Wiki  Seite](../wiki/OMP-Plugin-Development) angelegt, die eine Übersicht mit dem aktuellen Stand der PubId Plugins enthält

**Comment by nils-stefan-weiher** [comment]
URN Plugin wird mit OMP Version 3.1.0 mitgeliefert.
https://github.com/pkp/omp/tree/omp-stable-3_1_0/plugins/pubIds/urn

**Comment by withanage** [comment]
super.
