### ISSUE TITLE
do not show softcover as a file format, use only for isbn number

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#89]

**Comment by withanage** [comment]
![screenshot from 2016-10-27 10 02 23](https://cloud.githubusercontent.com/assets/1921992/19759291/8e159a02-9c2c-11e6-8fef-2b377c9b270e.png)

**Comment by ankosi** [comment]
@withanage Sorry, mir ist erst jetzt wieder eingefallen, dass wir für OMP bereits einmal eine andere Lösung gewählt hatten. Wir hatten uns darauf verständigt, dass wir bei Formaten, nur die ISBN gezeigt werden soll, in OMP bei der Einreichung kein PDF hochladen #55 

So ist es auch schon mal programmiert worden. 

Jetzt haben wir zwei verschiedene Lösungen. Das ist wahrscheinlich nicht besonders sauber. Sollen wir uns für eine entscheiden?

**Comment by withanage** [comment]
bei der andere hat sich nicht geändert. man sollte das Fromat als  "physical format"  markieren.

**Comment by ankosi** [comment]
Erledigt und Doku für das Anlegen von PoD-Formaten in OMP ins Publikationsdienste-Wiki aufgenommen.
