### ISSUE TITLE
piwik plugin for omp frontend

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#91]
Piwik Modul 
Gültig für alle Portale
- [x]  heiup
- [x]  heibooks
- [x]  propylaeum
- [x] xasia
- [x] arthistoricum

Dieses wurde vorgezogen, wegen der Installation von dem Piwik Server durch Serveradmins.
Alle Funktionen sind für Produktiven-instanzen installiert am 23.12.2016

**Comment by withanage** [comment]
@ankosi  dieses Ticket wurde  nach 82 für  priorisiert.

habe dann https://github.com/UB-Heidelberg/UBHD-OMPPortal/issues/67 von der "High" Liste rausgenommen, da es "Nice To have " war.

**Comment by ankosi** [comment]
Plugin-Installation noch in diesem Jahr, Programmierung der Datenauswertung ab Jan 2017 (Prio 2).

**Comment by withanage** [comment]
nein, man braucht die beide umzu funktioieren,

**Comment by withanage** [comment]
serverseitig wird der neue Admin übernehmen.
