### ISSUE TITLE
Fehlende Text-Spezikationen  für  E-Mail-Empfehlen-Funktion für Portale 

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPPortal#98]
@withanage 
#67 
Bitte den Text in der Empfänger-E-Mail an die Portalseiten anpassen. 

Gültig für alle Portale
- [x]  heibooks
- [x]  propylaeum
- [x] xasia
- [x] arthistoricum

**Comment by ankosi** [comment]
heiBOOKS-Portal:
[Absendervorname] [Absendernachname] empfiehlt Ihnen aus dem Verlagsprogramm von heiBOOKS, der E-Book-Plattform der Universitätsbibliothek Heidelberg, http://books.ub.uni-heidelberg.de/heibooks

**Comment by ankosi** [comment]
@nidame, @katbe, @bettinamueller, @lolalde 

Würdet Ihr bitte spezifizieren, wie der Text für Eure Portale lauten soll? Danke.

**Comment by nidame** [comment]
@withanage, @ankosi 
für CrossAsia-eBooks bitte folgenden Text:
[Absendervorname] [Absendernachname] empfiehlt Ihnen aus dem Programm von CrossAsia-eBooks, der Open-Access-Publikationsplattform für E-Books von CrossAsia, http://crossasia-books.ub.uni-heidelberg.de/xasia

**Comment by withanage** [comment]
Falls noch der Text für arthistoricum und propylauem da ist, könnte dieses Ticket abgearbeitet werden.
Noch bräuchte man das englische Text ,  falls es vom Standard Text abweichen sollte.

**Comment by nidame** [comment]
@withanage
englische Version für CrossAsia-eBooks
[name] recommends to you the following book published by CrossAsia-eBooks [link]
Danke

**Comment by withanage** [comment]
Arthistoricum 
[Absendervorname] [Absendernachname] empfiehlt Ihnen aus dem Angebot von arthistoricum.net – ART-Books [...]
[Absendervorname] [Absendernachname] recommends the following title from the publisher’s list of arthistoricum.net – ART-Books [...]

**Comment by withanage** [comment]
nur proyplaeum beide Texte und die englische Version für heibooks fehlen mir.

**Comment by withanage** [comment]
Propylaeum

[Absendervorname] [Absendernachname] empfiehlt Ihnen aus dem Angebot von Propylaeum – Propylaeum–eBOOKS [...]
[Absendervorname] [Absendernachname] recommends the following title from the publisher’s list of Propylaeum – Propylaeum–eBOOKS [...]

**Comment by ankosi** [comment]
@withanage 

Für heiBOOKS bitte:

[Absendervorname] [Absendernachname] recommends you

[Titeldaten]

published by heiBOOKS, the e-book platform of the Heidelberg University Library, http://books.ub.uni-heidelberg.de/heibooks

**Comment by withanage** [comment]
@ankosi  @nidame  @bettinamueller  @katbe  
alle portale sind jetzt mit Texte versehen, wie in obigen Kommentare stehen. Bitte testen

**Comment by withanage** [comment]
- [x]  heibooks
- [x]  propylaeum
- [x] xasia
- [x] arthistoricum

**Comment by ankosi** [comment]
heiBOOKS ok.

**Comment by withanage** [comment]
@nidame kannst Du noch bei Gelegenheit das neue Email-Template testen ?

**Comment by nidame** [comment]
@withanage
xA eBooks ist auch ok
