### ISSUE TITLE
Addblock plugins

### ISSUE THREAD

**Issue by withanage** [UB-Heidelberg/UBHD-OMPPortal#99]
Es könnte  vorkommen, dass vgwort  in einige plugins blockiert sind.
Zur Zeit keine  Lösung
TODO
- [x]  VGWORT aus Addblock Listen

- [x] Untersuchen, ob  eine sogenannte sicherer modus (ohne jegliche plugins, wie twitter, vgwort usw.  für Portal genutzt werden kann. Schwierigkeit, falls es vorher blockiert wird , kommt der Nutzer nicht auf die Seite.

**Comment by ghost** [comment]
Könnte man prüfen, ob jemand uBlock Origin verwendet und eine 
Popup-Warnung ausgeben?


Am 20.01.2017 um 13:52 schrieb Dulip Withanage:

**Comment by withanage** [comment]
theoretisch, ja aber auch  nur in haupt-seite, wenn  man auf der  Monogaph seite ist, dann ist es zu spät

**Comment by withanage** [comment]
@fkrb  vorschlägt eher eine transparente FAQ Lösung als   eine technische Lösung.
